### ISSUE TITLE
Feeding

### ISSUE THREAD

**Issue by Hallec** [CIRCL/AIL-framework#104]
Hello,

I have a doubt about "Feeding AIL with pystemon". In this section, one of the steps is: "Edit the file bin/feeder/pystemon-feeder.py and modify the pystemonpath path accordingly", but if I edit the pystemonpath variable inside the file: pystemon-feeder.py, (my pystemonpath is: /home/pystemon/pystemon.py), and then launch pystemon.py and pystemon-feeder.py, when opening the web browser, I don't see any information about pastesbins in AIL-Framework homepage. Could it be a problem with redis? Or Have I been editing the pystemonpath incorrectly?

Thank you!

**Comment by mokaddem** [comment]
Hello,

Since https://github.com/CIRCL/AIL-framework/commit/83db40104c05e4f3466cfd48a3da3ede627f47ec the modification of the path should be done in the configuration file (under bin/packages/config.cfg).

The doc has been corrected, thank you for pointing this out!

Can you try modifying the configuration file with your pystemon path and see if it works?

**Comment by Hallec** [comment]
Thank you, but I have followed step by step the instructions, and I don't know why but when I run the Flask_server.py, and visit the http://localhost:7000, a red message text: (with no running queues, or no feed) appears. I executed the LAUNCH.sh, and apparently redis, leveldb, queues and scripts are up. After that, I cloned pystemon's repository, and I modified the config.cfg, (In pystemonpath = I wrote the path: /home/hallec/pystemon), and finally I run pystemon and pystemon-feeder, but the message previously mentioned showed up. Is this project compatible with Ubuntu 16.04? Am I doing something wrong?

Thank you in advance for the help.

**Comment by mokaddem** [comment]
This project is fully compatible Ubuntu 16.04.
Could you again check that redis, leveldb, queues and scripts are running inside their screen session?
If so, what is the output of the Mixer module? Is the number of processed pastes 0?

**Comment by Hallec** [comment]
After running LAUNCH.sh, and executing screen -ls, the output is:

There are screens on:
	4369.Script	(01/03/17 23:43:15)	(Detached)
	4353.Queue	(01/03/17 23:43:15)	(Detached)
	4333.Logging	(01/03/17 23:43:15)	(Detached)
	4299.LevelDB	(01/03/17 23:43:15)	(Detached)
	4265.Redis	(01/03/17 23:43:14)	(Detached)

The mixer output is:
Empty Queues: Waiting...
...
Mixer; ; ; ;mixer_all All_feeders Processed 0 paste(s) in 30sec

Thank you!

**Comment by Hallec** [comment]
At last, I found my problem. The AIL tool is OK, but it was a problem feeding through pystemon. Thank you very much for all the help!

**Comment by Rotor123** [comment]
Hi,I don't know who to turn to, I was trying to make pystemon in the configuration as described above. But not understand how. now is such a line, but in the web interface is not working. pystemonpath = /home/b.bird/AIL-framework/pystemon/

**Comment by SteveClement** [comment]
@rotor123 can you be more specific what is not working?
Like are the screens running, which flavour of Linux or other are you using etc.

We have a Virtual Maching (Virtualbox) here: https://www.circl.lu/services/ail-training-materials/

You just need to log into the VM and you see how it should look.

We will add some explanatory pictures soon. As you need to start some of the services on first login (options 1-5, just select them and press enter to start the server, on the VM)

**Comment by IRB10** [comment]
@Hallec Can you specifically explain how you solved it, I get pastes through pystemon but when I run pystemon-feeder I keep getting None as displayed value, I hope you can help, and thanks in advance

**Comment by Hallec** [comment]
@IRB10 I solved this issue, with the fix I commented on pystemon repository: https://github.com/cvandeplas/pystemon/issues/64

But it was one year ago, and I have checked out the current repository, and the developer has made a lot of changes in the code, so surely this fix doesn't work now. Sorry, if you can post a log with the error, I'll try to help you out, or probably you could find some quality support in the main repository of pystemon: https://github.com/cvandeplas/pystemon

**Comment by annetteshajan** [comment]
Can you explain how you did this exactly?
The feeder is not working at all for me
