### ISSUE TITLE
Cannot Run Flask Server

### ISSUE THREAD

**Issue by kajogo777** [CIRCL/AIL-framework#117]
i followed the installation instructions and finally tried to start the flask server

`./Flask_server.py`

but i keep getting this error

`Traceback (most recent call last):
  File "./Flask_server.py", line 35, in <module>
    import Flask_search
  File "./Flasks/Flask_search.py", line 31, in <module>
    cfg.get("Indexer", "register"))
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
ConfigParser.NoOptionError: No option 'register' in section: 'Indexer'
`
i am not sure if there is something wrong with my environment or there is actually a bug

**Comment by olafhartong** [comment]
Same here on a clean Jessie install, followed the install script to the letter

**Comment by kajogo777** [comment]
@olafhartong checking out to the previous commit worked, i recommend this as a temporary work out
`git checkout -b temp_branch 8435520d8b65bd1fd8286eb97b7b1aa500c2df00`

**Comment by adulau** [comment]
Which version of Flask are you running?

**Comment by mokaddem** [comment]
Indeed, there is a missing field in the configuration file _config.cfg.sample_.
This have been corrected in the pull request #116.
Sorry for the inconvenience.

**Comment by kajogo777** [comment]
my flask version is 0.12.1

**Comment by kajogo777** [comment]
@mokaddem  thanks for the fast fix, i will try it again after the merge

**Comment by adulau** [comment]
and it's now merged ;-)

**Comment by olafhartong** [comment]
Thanks alexandre, it is running fine now
