### ISSUE TITLE
Feed sources

### ISSUE THREAD

**Issue by kajogo777** [CIRCL/AIL-framework#118]
is it possible to add a custom feed source using a special python script? if so how do i do this?

example feeds i have in mind:
- offline feeds as CSV for example

- web scrapping scripts

**Comment by adulau** [comment]
The easiest way to do it is to feed the global queue like done in https://github.com/CIRCL/AIL-framework/blob/master/bin/import_dir.py or via the mixer on a specific ZMQ pub-sub channel.

The format of input is:

<id-archive-ref> Base64(gzip compressed(raw data))

**Comment by kajogo777** [comment]
thanks

is it currently possible to import data with the existing implmenetation?

because i want to know what is already possible as not to re-invent the wheel

**Comment by mokaddem** [comment]
AIL completely support text data. Some features of AIL might also work for other data type.
You can feed AIL with the ```import_dir.py``` script. 
Does that answer your question? Otherwise, could you be more precise?
