### ISSUE TITLE
Credential module to find firstname/lastname combination in email based on a fixed list

### ISSUE THREAD

**Issue by adulau** [CIRCL/AIL-framework#122]
Credential module to find firstname/lastname combination in email based on a fixed list.

Something like `John Smith` would:

~~~~
jsmith@
john.smith@
smith.john@
smithj@


jsmith<numerical value>@
john.smith<numerical value>@
smith.john<numerical value>@
smithj<numerical value>@
~~~~

And create additional notification in the warning queue.

**Comment by mokaddem** [comment]
Does #131 satisfy this issue?
Credentials received before the update will not yield results...

**Comment by adulau** [comment]
Thank you. This makes sense. Nice work.
