### ISSUE TITLE
import_dir.py - large files - MemoryError

### ISSUE THREAD

**Issue by garanews** [CIRCL/AIL-framework#140]
I am receiving this error trying to import ~300MB gzip file:

Traceback (most recent call last):
  File "./import_dir.py", line 92, in <module>
    socket.send('{} {} {}'.format(args.channel, path_to_send, base64.b64encode(messagedata)))
  File "/usr/lib/python2.7/base64.py", line 53, in b64encode
    encoded = binascii.b2a_base64(s)[:-1]
MemoryError

Probably the function base64 doesn't support large files.
Any idea?

**Comment by mokaddem** [comment]
Perhaps, it could be worth working with stream instead of string.
Thank you for reporting!

**Comment by Terrtia** [comment]
The [ail-feeder-leak](https://github.com/ail-project/ail-feeder-leak) feeder can be used for importing and chunking large files.
