### ISSUE TITLE
./AILENV/bin/activate: No such file or directory

### ISSUE THREAD

**Issue by rubinsaifi** [CIRCL/AIL-framework#144]
Hi,

I followed instructions from repo.
but when i source to activate it says there is not such file or directory
there is no directory named AILENV in AIL-framework

fluorine@radon:~/AIL-framework$ git log -1
commit a25fc828e3e5969a25cae8aa8556b3d47e180840
Merge: bb128a5 a8dc923
Author: Alexandre Dulaunoy <a@foo.be>
Date:   Thu Aug 24 17:07:21 2017 +0200

    Merge pull request #139 from mokaddem/indexer_register_fix

    Fixed bug: No CR between indexes in all_index.txt file
fluorine@radon:~/AIL-framework$ . ./AILENV/bin/activate
-bash: ./AILENV/bin/activate: No such file or directory

Can you please help me installing this.
Thanks

**Comment by mokaddem** [comment]
Hi,
Does the install script ```./installing_deps.sh``` complete successfully?

**Comment by megan201296** [comment]
I am encountering the same issue. From what I can tell @mokaddem `./installing_deps.sh` did complete successfully.

**Comment by mokaddem** [comment]
Did you launch ```./installing_deps.sh``` from the ```AIL-framework/```folder? Perhaps you started it from another location... 
For the moment, the install script is path dependent.

**Comment by rubinsaifi** [comment]
@mokaddem i cleaned up, cloned and retried the installation  again and this time it worked.
marking this for closure.
