### ISSUE TITLE
./installing_deps.sh incomplete install

### ISSUE THREAD

**Issue by p0pps** [CIRCL/AIL-framework#165]
Hello,

I try to install AIL-framework but the installing_deps.sh didn't works,
I have this error :

mv: cannot stat 'temp/canvasjs-1.9.10-stable/jquery.canvasjs.min.js': No such file or directory                                                             

I don't undestand why, I launch it from the AIL-framework/folder and I in root..

Thanks for your answer.

**Comment by mokaddem** [comment]
Hi,
The ``var/www/update_thirdparty.sh`` script was causing the issue.
canvasjs changed the folder organisation.
Thanks for the report!
