### ISSUE TITLE
Screen Error

### ISSUE THREAD

**Issue by p0pps** [CIRCL/AIL-framework#168]
Hello,
I've few problems with AIL..
Nothing is displayed in my DashKeyboard (Trendig charts and modules statics works) :

![capture](https://user-images.githubusercontent.com/34537872/34203488-9ca6520c-e57b-11e7-8753-f4b4362a2fd7.JPG)

And I suppose it's because of few screen error.
When I attached screens, Script_AIL, Queue_AIL and LevelDB_AIL output seem not good.

1.I've no output for Script_AIL
2 This error for LevelDB_AIL
![leveldb_output](https://user-images.githubusercontent.com/34537872/34203495-a46c5bbc-e57b-11e7-9243-e5bb25c47c54.JPG)

3.And this output for Queue:

![queue_output](https://user-images.githubusercontent.com/34537872/34203501-a738248e-e57b-11e7-8558-b68bd6558eb1.JPG)

Thank you for your help.

**Comment by mokaddem** [comment]
Hello,
Following your points:
1. You should have output for the script screen. Did you navigate through windows? slide 38 of [this presentation](https://github.com/CIRCL/AIL-framework/blob/master/doc/presentation/ail-training-november.pdf) shows useful commands.
Especially, what is the output of the ``Mixer.py`` script (second window)?

2. Can you check that ``AIL-framework/LEVEL_DB_DATA/`` contains a folder names ``2017``?

3. This is a normal output for this session. See slide 31 of [the presentation](https://github.com/CIRCL/AIL-framework/blob/master/doc/presentation/ail-training-november.pdf)

**Comment by p0pps** [comment]
Thank you for the rapidity of your answer.

Following my point :
   1.  The output of Mixer.py is : (I check it with C-a n after attached the Script)
```

sleeping
sleeping
sleeping
.
.
.
sleeping
```



  2.  No there is no folder names `2017 `,

**Comment by mokaddem** [comment]
1. That's the wrong screen :(
You should see ``Empty Queues: Waiting...`` and every 30sec, it should print the number of processed pastes.
2. Try to create it and see if it works. (However, it does not impact if you are receiving pastes or not)

**Comment by p0pps** [comment]
1. Yeah sorry :S 
    Indeed I've this output `Empty Queues: Waiting...`
2. I did but no it didn't work..

So I'm confused, if my output are ok I don't understand why DashKeyboard and my Browse important pastes didn't work and not displayed data..

**Comment by mokaddem** [comment]
Can you check that (in [bin/package/config.cfg](bin/package/config.cfg)):
- ``[ZMQ_Global] -> address, bind``
- ``[Directories] -> pystemonpath``

matches your configuration.

Also can you confirm that [test-zmq.py](https://github.com/CIRCL/AIL-framework/blob/master/bin/feeder/test-zmq.py) outputs data?

If you are using pystemon, you want to change the URL inside [test-zmq.py](https://github.com/CIRCL/AIL-framework/blob/master/bin/feeder/test-zmq.py) so that it also matches your configuration:
``socket.connect ("tcp://crf.circl.lu:%s" % port)``
by default pystemon is on:
``socket.connect ("tcp://127.0.0.1:5556")``

**Comment by p0pps** [comment]
In [ bin/package/config.cfg](url) :

- ` [ZMQ_Global]`
  address =[ tcp://127.0.0.1:65222 ](url)(I put the port that I use to browse AIL framework..)
  bind = [tcp://127.0.0.1:5556](url)

- `[Directories]`
  pystemonpath = [/home/pystemon/](url) (it's where pystemon is)

I have no outputs when when I execute python test-zmq.py.

So I have to change `socket.connect ("tcp://crf.circl.lu:%s" % port) `by
 `socket.connect ("tcp://127.0.0.1:5556")` ?


Thank you for the rapidity of your answer;

**Comment by p0pps** [comment]
I did the modification, 

Now I have new output for` Script_AIL` (1) and `Mixer.py `(2)

(1) 
![script_window1](https://user-images.githubusercontent.com/34537872/34253577-7e87b360-e648-11e7-8620-63237de22a58.JPG)
(2)
![mixer](https://user-images.githubusercontent.com/34537872/34253581-82014e3e-e648-11e7-85e1-84c7cc9f9aad.JPG)

Now `Mixer.py` take into account the pastes, unfortunately in AIL API my DashKeybord an Browse Important Pastes still don't have data..

**Comment by mokaddem** [comment]
Good! At least the platform is having data input.
``Browse important pastes`` will only show pastes that have been through the alert module.
What you call 'DashKeybord' is this the default landing page (``Dashboard`` tab)? If yes, can you check in your browser console if anything went wrong?

**Comment by p0pps** [comment]
Yes thanks you, it progress slowly but it progress !
Ok so it's for particularly pastes ?

Yes I mean `Dashboard` sorry,
What do you mean by  'you check in your browser console if anything went wrong?'

**Comment by mokaddem** [comment]
``Browse important pastes`` will only show pastes that have been declared as an alert in one module.
For example, a paste containing phone numbers will be declared as an alert only if it contains at least 4 phone numbers (defined in the module).

By *you check in your browser console* I mean, open the console of your browser (F12 for both chrome and Firefox). If nothing is displayed in your dashboard but the framework is receiving data, it is likely that something went wrong browser-side.

**Comment by p0pps** [comment]
Ok, thank you.

Yeah sorry ^^ 
Hum, I don't know why but I reboot my server and it seem works !! 
Now I have this display 
![dashboard1](https://user-images.githubusercontent.com/34537872/34262138-bf1c109c-e66b-11e7-99e0-260eb51da569.JPG)

Thank you very much for your help !! :)

**Comment by mokaddem** [comment]
You are welcome!
