### ISSUE TITLE
No such file or Directory (Feeder)

### ISSUE THREAD

**Issue by MrDoubts** [CIRCL/AIL-framework#169]
Everything is installed and the web server is running.
Some minutes after launching the feeder it gives this error and everything stops:

Traceback (most recent call last):
 File "pystemon-feeder.py", line 64, in <module>
   messagedata = open(pystemonpath+paste).read()
IOError: [Errno 2] No such file or directory: '/home/gt/pystemon/archive/codepad.org/2018/01/03/8RsQZOlJ.gz'

The directory doesn't really exist and I made a FLUSHALL to redis but the problem persists.

Any idea?
Thanks,

**Comment by mokaddem** [comment]
Hi,
Can you check that the file and directories exist; and that you have correct permissions on them? 
Normally, ``Pystemon`` creates files and directories by itself.

**Comment by MrDoubts** [comment]
There are some files and directories created but the ones that give error doesn't exist at all.

**Comment by adulau** [comment]
@MrDoubts Could you check with the latest version of the feeder?

**Comment by mokaddem** [comment]
If it is partially working for you, don't hesitate to adapt the ``sleep_time`` parameter so that they better fit your system.
And if you do, don't hesitate to share them so that you could help us fine tunning them. :)

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
