### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by p0pps** [CIRCL/AIL-framework#174]
Hello,

I've install AIL since one month and everything worked good, but now when I tried to access to the module Terms managements I've this error : 

![capture](https://user-images.githubusercontent.com/34537872/35800175-7d698c26-0a68-11e8-98b1-f33d3f6fa199.JPG)

Thanks for your help

**Comment by adulau** [comment]
Could you share the output log of the https://github.com/CIRCL/AIL-framework/blob/master/var/www/Flask_server.py ? Thank you.

**Comment by p0pps** [comment]
Of Course : 

![captureflask](https://user-images.githubusercontent.com/34537872/35805123-ed5ad618-0a7a-11e8-95ce-f7c1ca340fd9.JPG)

**Comment by p0pps** [comment]
And when I try to add some term to the black or tracked list, it seem works I'ven't error message

**Comment by adulau** [comment]
It seems to be a unicode ascii issue. Interesting. Is the term in ASCII 7 bits? or UTF-8?

**Comment by p0pps** [comment]
Sorry but I don't know how to check that...

**Comment by p0pps** [comment]
Do you have any idea or track ?
I tryed to change code by adding 

#!/usr/bin/env python
#-*- coding: utf-8 -*-

in some file code but it was useless.

I really don't know where looking for..

**Comment by p0pps** [comment]
At the top of the screen it misses this line 

![image](https://user-images.githubusercontent.com/34537872/35982425-11924044-0cf0-11e8-9fc3-999f1c2d363d.png)

I don't know if that can help more

**Comment by p0pps** [comment]
Problem fixed ! 
It's was an unicode problem.
Flask didn't "support" unicode so I had this code into Flask_server.py

![image](https://user-images.githubusercontent.com/34537872/36030446-8e674ca6-0da7-11e8-94cd-dc9e6f55ddb7.png)

**Comment by mokaddem** [comment]
Great to hear!
Thanks for the feedback!
