### ISSUE TITLE
No paste in "Browse Important Pastes" panel

### ISSUE THREAD

**Issue by jeromeleonard** [CIRCL/AIL-framework#175]
OS: Ubuntu 16.04
installed with git clone and installing_deps.sh.

After several trials,there is no paste in the "Browse Important Pastes" panel in the web UI while there are WARNING logs.

**Comment by mokaddem** [comment]
Hi,
Can you check in the screens that the script ``bin/alertHandler.py`` does not output and error?

**Comment by jeromeleonard** [comment]
I have only this line: 
```
Misp keys not present
```

**Comment by mokaddem** [comment]
Just to see if it is client or server side, can you check in redis ``localhost -p 2018`` if keys with prefix ``WARNING_`` are there?
``redis-cli> keys WARNING_*``
If yes, it may be client side.

**Comment by Kayama75** [comment]
I have the same problem, everything works except that!

**Comment by mokaddem** [comment]
#181  updated python3 dependencies in ``install_dependencies.sh`` which caused the ``alertHandler.py`` script to crash (responsible to index *important pastes*).

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
