### ISSUE TITLE
No Infos, no Warnings, Data not searchable

### ISSUE THREAD

**Issue by ph34tur3** [CIRCL/AIL-framework#205]
Dear CIRCL team,

thank you very much for this project. I like your work and hope you can help me out here.
I am having trouble to get every feature up and running.

OS:
- Installed AIL on Ubuntu 16.04 (Host OS, Guest OS [both vmware and virtualbox])
- CIRCL training VM 

what works:
- building the project successfully.
- starting everything (1->5) using bin/LAUNCH.sh and var/www/Flask_server.py.
- importing pastes using import_dir.py. (the directory structure is okay)
- viewing the graphs and the processing through localhost:7000 .

what does not work:
- getting INFO/WARNING/CRITICAL messages.
- searching through the pastes.

I've downloaded the pastes by myself and imported them using import_dir.py and I even tried to import them with a custom script of mine, but the result is still the same.

Is there anything you can think of why this happens?
thanks in advance

EDIT:
ModulesInformationV2.py shows the activity of the running/idling queues. Some (quite important) queues/scripts are not running, like Mail, Credentials etc. In the beginning it says "no data" and after a while it says "Stuck or idle, restarting in x s"
Even the -k 1 switch doesn't work.

**Comment by mokaddem** [comment]
Hello!
Did you install AIL from scratch or did you use the provided VM?
If you used the VM, could you please ``git pull`` (as it may not be up-to-date) and try again?

**Comment by ph34tur3** [comment]
Hi @mokaddem ,
thank you for your rapid reply.
I did both. I tried using the VM once and I installed AIL from scratch multiple times.
Since your are mentioning the VM, I am now switching to it.

Steps I've done since your last message:
- fresh import of the VM into virtualbox
- fixed the locales, did apt update & upgrade
- git pull for recent changes
- launched "python3_upgrade.sh"

The last step produced some errors I needed to resolve.
- pip3 10.0.1 throws an error, saying that python can't resolve main in "from pip import main". I fixed that by replacing "pip3" with "python3 -m pip"
- some calls needed extra permissions, so I added "sudo -H" and it proceeded a little further (e.g. installing the requirements.txt)

**Do you need to resolve these errors when you install / upgrade your instance?**
After multiple attempts I still get the following error:
`
+ pushd faup/src/lib/bindings/python/
~/AIL-framework/faup/src/lib/bindings/python ~/AIL-framework
+ python3 setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 2] No such file or directory: '/usr/lib/python3.5/site-packages/test-easy-install-26195.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/lib/python3.5/site-packages/

This directory does not currently exist.  Please create it and try again, or
choose a different installation directory (using the -d or --install-dir
option).
`
How do I resolve this? Or am I actually doing something wrong in my previous steps?
Thank you in advance!

**Comment by ph34tur3** [comment]
Hi @mokaddem ,
I managed to solve the problem in a different vm. The main problem after some debugging is the import_dir.py script. The data files are opened with gzip.open() and that results in a plain text file written to the PASTES dir. Your Paste class wants gzip encoded files in the PASTES dir, which results in empty strings interpreted by the analyzer scripts.

Thank you for your help!

Although this issue is fixed - why is it so hard to upgrade an existing AIL installation?

**Comment by Terrtia** [comment]
hi @ph34tur3,

the install and upgrade issue should be fix with cd6734f70430024bf02fc3494f361a8d4be6297f

thank for you feedback!

**Comment by adulau** [comment]
Let us know if the fix cd6734f70430024bf02fc3494f361a8d4be6297f solves the issue. In the mean time, we close the issue, feel free to reopen if the issue persists.
