### ISSUE TITLE
trouble with a fresh install

### ISSUE THREAD

**Issue by tcccorp** [CIRCL/AIL-framework#218]
Hello, 

I tried to install AIL on a fresh ubuntu 16.04  ( with last updade/upgrade) . I followed instruction on README but I have the error below .   I don't know if it is an issue with the server or with modules ( you will find the result of pip3 freeze )  

Thank

(AILENV) root@crawl-scrap:/opt/AIL-framework/var/www# more ./Flask_server.py
Misp not connected
The HIVE not connected
Traceback (most recent call last):
  File "./Flask_server.py", line 66, in <module>
    importlib.import_module(name)
  File "/opt/AIL-framework/AILENV/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "modules/Tags/Flask_Tags.py", line 34, in <module>
    clusters = Clusters(skip_duplicates=True)
  File "/opt/AIL-framework/AILENV/lib/python3.5/site-packages/pymispgalaxies/api.py", line 267, in __init__
    clusters.append(json.load(f))
  File "/usr/lib/python3.5/json/__init__.py", line 265, in load
    return loads(fp.read(),
  File "/opt/AIL-framework/AILENV/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3992: ordinal not in range(128)

pip3 freeze

adns===1.4-py1
asciimatics==1.9.0
asn1crypto==0.24.0
backcall==0.1.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
click==6.7
colorama==0.3.9
crcmod==1.7
cryptography==2.2.2
cycler==0.10.0
cymru-services==1.4
decorator==4.3.0
dnspython==1.15.0
DomainClassifier==0.7
Flask==1.0.2
future==0.16.0
idna==2.7
ipaddress==1.0.22
IPy==0.83
ipython==6.4.0
ipython-genutils==0.2.0
itsdangerous==0.24
jedi==0.12.1
Jinja2==2.10
jsbeautifier==1.6.2
jsonschema==2.6.0
kiwisolver==1.0.1
langid==1.1.6
Logbook==1.4.0
MarkupSafe==1.0
matplotlib==2.2.2
mmh3==2.5.1
networkx==2.1
nltk==3.3
numpy==1.14.5
olefile==0.43
parso==0.3.0
peepdf==0.4.2
pexpect==4.6.0
phonenumbers==8.9.9
pickleshare==0.7.4
Pillow==5.2.0
pkg-resources==0.0.0
prompt-toolkit==1.0.15
psutil==5.4.6
ptyprocess==0.6.0
pubsublogger==1.2.2
pybloomfiltermmap==0.3.15
pycountry==18.5.26
pycparser==2.18
pyfaup==1.0
pyfiglet==0.7.5
Pygments==2.2.0
pymisp==2.4.93
pymispgalaxies==0.1
pyparsing==2.2.0
PySocks==1.6.8
pytaxonomies==0.5
python-dateutil==2.7.3
python-Levenshtein==0.12.0
python-magic==0.4.15
pythonaes==1.0
pytz==2018.5
pyzmq==17.0.0
redis==2.10.6
requests==2.19.1
SFlock==0.3.5
simplegeneric==0.8.1
six==1.11.0
ssdeep==3.3
terminaltables==3.1.0
textblob==0.15.1
texttable==1.4.0
thehive4py==1.4.4
tlsh==0.2.0
traitlets==4.3.2
urllib3==1.23
wcwidth==0.1.7
Werkzeug==0.14.1
Whoosh==2.7.4
zmq==0.0.0

**Comment by tcccorp** [comment]
Hello, 

I tried but it still fail    .  I have an issue with python's module . I tried to install the right version but without success  :(   to be honest, I tried to install docker but there is an error too. I'm going to install a new vps without updrade.I'll keep you informed 

Thanks for your help 


Successfully built thehive4py
peepdf 0.4.2 has requirement colorama==0.3.7, but you'll have colorama 0.3.9 which is incompatible.
peepdf 0.4.2 has requirement Pillow==3.2.0, but you'll have pillow 5.2.0 which is incompatible.
sflock 0.3.5 has requirement click==6.6, but you'll have click 6.7 which is incompatible.
sflock 0.3.5 has requirement python-magic==0.4.12, but you'll have python-magic 0.4.15 which is incompatible.
        * Configuration up-to-date

**Comment by tcccorp** [comment]
I confirm you,  you have to make the install before making an apt upgrade :(   now it works  . 

I have a question, why do you need tor ? 

Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2471/sshd
tcp        0      0 0.0.0.0:7000            0.0.0.0:*               LISTEN      4567/python3
tcp        0      0 127.0.0.1:9050          0.0.0.0:*               LISTEN      9823/tor
tcp        0      0 0.0.0.0:6379            0.0.0.0:*               LISTEN      3831/redis-server *
tcp        0      0 127.0.0.1:5004          0.0.0.0:*               LISTEN      3999/python3
tcp        0      0 0.0.0.0:6380            0.0.0.0:*               LISTEN      3841/redis-server *
tcp        0      0 127.0.0.1:5005          0.0.0.0:*               LISTEN      3991/python3
tcp        0      0 0.0.0.0:6381            0.0.0.0:*               LISTEN      3847/redis-server *
tcp        0      0 127.0.0.1:6382          0.0.0.0:*               LISTEN      3868/ardb-server
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      164/rpcbind

**Comment by Terrtia** [comment]
We use tor in `tor_fetcher.py`.
We check the validity of a .onion url
