### ISSUE TITLE
date sorting for "Show infomation" in  Terms frequency: Management interface

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#219]
Hello,

There is a small bug, when we try to sort by date the  concerning paste(s) about a keyword.
Date has the following format: DD/MM/YYYY, so pastes are sorted in the same format, so when we try to sort them, it is hard to get for most recent first or last.

When I sort them, i have:
01/07/2018
02/07/2018
05/07/2018
05/07/2018
05/07/2018
27/06/2018
28/06/2018
29/06/2018
30/06/2018

So I've to change many pages to get the actual day.

Best regards

**Comment by Terrtia** [comment]
Hello,
thank for the reporting !

you right, we should use the YYYY/MM/DD format

**Comment by Terrtia** [comment]
3b4e2a18aa0063aacbcc156ddc670bb956948ccb Should cover the issue.

Can you confirm ?

**Comment by FafnerKeyZee** [comment]
Working ! 

Thanks for the quick fix :)

**Comment by Terrtia** [comment]
Thanks for the feedback !
