### ISSUE TITLE
Mail notification possibility to add a link concerning the past

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#220]
Hey,

Is it possible to add a link or a reference number, when we got a mail for a new occurence ? 

Ie:
New occurrence for term: XXXXXX
http://yourdomain/showsavedpaste/?paste=linktothepaste

Best regards,

**Comment by Terrtia** [comment]
Hi,

Good idea we need to modify `NotificationHelper.py` and add tags notification.

**Comment by Terrtia** [comment]
should be fix with fa38434e04a9296addc8d20a9ae6b67da4b619d7

can you please confirm ?

**Comment by FafnerKeyZee** [comment]
It works like a charm !!!

**Comment by FafnerKeyZee** [comment]
It's working \o/ Thanks for the fix .]
