### ISSUE TITLE
The Hive auto export always working

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#221]
Hey,

I configured AIL to work with TheHive, when I got to the page: 
http://myinstance/PasteSubmit/enable_hive_auto_alert
The hive auto export is marked as Disabled (in red), but it is still populating my TheHive instance. With the selected tags.

**Comment by FafnerKeyZee** [comment]
Ok, I forced this uri: /PasteSubmit/disable_hive_auto_alert and looks it did the job...

**Comment by Terrtia** [comment]
Hey !

thank for the report,

**Comment by Terrtia** [comment]
should be fix with 4b8c26dec8b5d72ef75f062a06ace2e5d9c50bd4

can you please confirm ?

**Comment by FafnerKeyZee** [comment]
Hey !
For the moment it seems working. I activated it few hours, then stop it and didn't get alert since.

Best Regards
