### ISSUE TITLE
Authent and users management

### ISSUE THREAD

**Issue by tcccorp** [CIRCL/AIL-framework#223]
Hello, hope it is the right place to post this request 

I tested AIL and I love it :)  but it is directly connected to internet . Do you plan ti add a login page and  something to manage users ? Same about the configuration of email server ( when AIL detects a keyword for IE)

Thanks

Serge

**Comment by adulau** [comment]
Thank you for the feedback.

It's something we have in the long list of features to be implemented ;-) In the meantime, a reverse proxy with an user-authentication can do the job.

**Comment by mokaddem** [comment]
Duplicate of #155

**Comment by adulau** [comment]
It's now fixed in release v2.0 - d937c03ddbbf371ecc8e3f3525a1d31069a5ecb1

**Comment by tcccorp** [comment]
Hello, Thanks for this new version :) 

Serge
