### ISSUE TITLE
import_dir.py stringIO

### ISSUE THREAD

**Issue by terrieristorg** [CIRCL/AIL-framework#251]
Since this error is different from the other one I seem to have created in trying to fix this bug (see [Stuck queues](https://github.com/CIRCL/AIL-framework/issues/244)) I've created a new thread for it

In import_dir.py running in AILENV:

`Traceback (most recent call last): File "./import_dir.py", line 89, in <module> out = StringIO.StringIO() AttributeError: type object '_io.StringIO' has no attribute 'StringIO'`

Thank you for any help in resolving this  issue.

**Comment by Terrtia** [comment]
Hey @terrieristorg,

This should be fix with  ebad2af

Can you please confirm ?

The date directory tree is no longer needed. He will be generated if he don't exist.

**Comment by Terrtia** [comment]
fixed with ebad2af
