### ISSUE TITLE
VirusTotal Api key

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#253]
Hey,

Not a bug, just a little info. When browsing the source code and playing with the web interface, we can see that we can use a VT key to upload file in order to scan them. Is it possible to add a sample file in the repo ?

I create the following file : 

**%AIL_DIR%/configs/keys/virusTotalKEYS.py**

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

vt_key = 'MY_API_KEY'
```

**Comment by mokaddem** [comment]
Thanks for the report!
Indeed, we forgot to add it.
73622acab38be223d51b5858d88be53ead78de47 fix this.
