### ISSUE TITLE
Potential Graphical Bug in WEB interface

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#254]
Hey,

On the dashboard page, there is a small bug for the section:  
"Total pastes since 10 min."
When I load the page It is blank for few minutes, but if I click inside, few seconds after a graph appears.

I've this bug with:
Firefox (Debian 10) : 52.9.0 (64-bit)

Best regards,

**Comment by FafnerKeyZee** [comment]
After deeper analyze it seems that is not a bug from AIL.

I close the ticket .

Best regards,

**Comment by mokaddem** [comment]
Thanks for the update!
