### ISSUE TITLE
[Queue] DomClassifier always incrementing

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#255]
Hey,

When I check the "Working queues" list on the dashboard, I can see that the queue for DomClassifier is permanently increasing. 
The other jobs are increasing and decreasing, but not for DomClassifier. Is is the attended behavior ?

Best regards,

**Comment by Terrtia** [comment]
Hey,
This module need some time to extract domains/hostnames/IP. Depending of the DNS response time, the queue for DomClassifier can increase quite a lot.

You can check the DomClassifier output on the Script_AIL screen.

Best regards,

**Comment by FafnerKeyZee** [comment]
Ok, 
After we views with Script_AIL, Yes, it is running correctly (got a new paste). So it's ok. Sorry for the issue.
