### ISSUE TITLE
Typo for running "PreProcessFeed.py"

### ISSUE THREAD

**Issue by FafnerKeyZee** [CIRCL/AIL-framework#256]
Hey !

Again a new issue :p (I asked before flooding)
When I try to run PreProcessFeed from the screen script, I got the following error:

> bash: ./PreProcessFeed.py: No such file or directory

I think it is due to a typo in the name of the file :  	AIL-framework/bin/preProcessFeed.py
Which should be : AIL-framework/bin/PreProcessFeed.py

Am I right ?

**Comment by FafnerKeyZee** [comment]
Got the same for misp_the_hive_feeder
bash: ./misp_the_hive_feeder.py: No such file or directory

But we have the file: AIL-framework/bin/MISP_The_Hive_feeder.py

**Comment by Terrtia** [comment]
hey @FafnerKeyZee  !
Thank for all the bugs report !

You right, the filename and the config name shouldn't be different. 
This should be fixed with ead4dba.

**Comment by Terrtia** [comment]
This script is used as an example of how pre-process a feed.
You can use it to create your own pre-process script.

**Comment by FafnerKeyZee** [comment]
Oh ok. Issue can be closed :)

**Comment by annetteshajan** [comment]
@FafnerKeyZee can you let me know how exactly you started running MISP and how to access its web interface?
Everytime i run ./MISP_The_Hive_feeder.py I just get:
```
Misp keys not present
The HIVE keys not present

```
