### ISSUE TITLE
term management upgrade

### ISSUE THREAD

**Issue by Terrtia** [CIRCL/AIL-framework#274]
show tags
auto push to MISP, the Hive

**Comment by adulau** [comment]
- [ ] Add tag when keyword is matching (e.g. different constituencies) 
- [ ] Add term management via external API 
- [ ] Add MISP and TheHive interface to push when a term is matching

**Comment by Terrtia** [comment]
- [ ] Add new tags to the auto push list

**Comment by elbae** [comment]
- [ ] Edit term value
- [ ] Edit Notification Email

**Comment by Terrtia** [comment]
Fixed with term tracker v2
