### ISSUE TITLE
Tag search failure on imported pastes due to relative path instead of full path

### ISSUE THREAD

**Issue by ngsimon** [CIRCL/AIL-framework#280]
The Web server doest not properly handle the pastes imported by the script "import_dir.py". 
The pastes cannot be properly displayed and trigger a web server error 500.

The error is due to the paste path is using a relative path instead of a full path.

Example of request /Tags/get_tagged_paste?ltags=infoleak:automatic-detection="onion"

Webserver result:
![image](https://user-images.githubusercontent.com/26148566/47354673-9c0d1200-d6bf-11e8-9f4d-8c14f6aeb67a.png)

**Comment by ngsimon** [comment]
A workaround would be in Flask_Tags.py to concatenate the AIL root directory to all pastes having a path  beginning with "import_dir/import_dir>>"

**Comment by Terrtia** [comment]
hey @ngsimon !
Thank for the report !

This should be fix with ea7fd8d54ce2312e3cbf6538f4855700618b7f5a and 8a6ac6be1e124fdd84f212a3095303abb30fe04a.

But some functions are only using absolute paths (like tag editing). AIL should't use any absolute paths.
I will refactor them asap.

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
