### ISSUE TITLE
Web Queue stuck

### ISSUE THREAD

**Issue by v0ris** [CIRCL/AIL-framework#289]
Dear team!

I have a problem with Web queue. After a longer period of time it going to stuck. When I run it manually, I get a lot of timeout messages:

The DNS operation timed out after 2.001352310180664 seconds
(1, set())
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
The DNS operation timed out after 2.000058174133301 seconds
The DNS operation timed out after 2.0013389587402344 seconds
The DNS operation timed out after 2.0003206729888916 seconds
The DNS operation timed out after 2.0012855529785156 seconds
The DNS operation timed out after 2.0013458728790283 seconds
The DNS operation timed out after 2.0001461505889893 seconds
(6, set())
wwww3schools.com 55081 US United States
The DNS operation timed out after 2.00104022026062 seconds
(1, set())
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
github.com 36459 US United States
The DNS operation timed out after 2.0000851154327393 seconds
The DNS operation timed out after 2.000082015991211 seconds
The DNS operation timed out after 2.0000967979431152 seconds
The DNS operation timed out after 2.000091552734375 seconds
The DNS operation timed out after 2.000084161758423 seconds
The DNS operation timed out after 2.000227451324463 seconds
The DNS operation timed out after 2.001420736312866 seconds
The DNS operation timed out after 2.0014162063598633 seconds

**Comment by v0ris** [comment]
Microsoft, but when I perform a simple "host" command on the AIL OS it does not take to long lime:

linux.com has address 151.101.1.5
linux.com has address 151.101.129.5
linux.com has address 151.101.65.5
linux.com has address 151.101.193.5
linux.com mail is handled by 10 smtp2.linuxfoundation.org.
linux.com mail is handled by 10 smtp1.linuxfoundation.org.

real    0m0,108s
user    0m0,010s
sys     0m0,004s

**Comment by FafnerKeyZee** [comment]
Did you specify it inside the config file ? Did you test with an other server in the config file ?

**Comment by v0ris** [comment]
Thank you for the respondes.

I have found the solution:

In the "bin/packages/lib_refine.py" have a hard coded address: (Line 108)

 resolver.nameservers = ['149.13.33.69']

After I change it to my own dns server the queue work perfectly. 

I think it would be better if the Web.py dns server variable be a configurable via config.cfg file.

**Comment by v0ris** [comment]
Thank you for the respondes.

I have found the solution:

In the "bin/packages/lib_refine.py" have a hard coded address: (Line 108)

 resolver.nameservers = ['149.13.33.69']

After I change it to my own dns server the queue work perfectly. 

I think it would be better if the Web.py dns server variable be configurable via config.cfg file.

**Comment by Terrtia** [comment]
hey @v0ris,

Thank for the report !
Should be fix with cb41c54
