### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by tcccorp** [CIRCL/AIL-framework#295]
Hello , 

I have issues with AIL  . My previous version has been installed just after "pass  the salt" and the workshop .  I had some trouble  server crash .  Last week  I upgraded  with the lastest version and now it is worst :(

after some tries , I renamed the AIL directory and make a fresh install . 

since one week , I note : 
- there is nothing on the trending chart part, modules statistics and sentiment trending 
- when I use terms management, there no data ( i tested with simple word as command, leak, ...) . If I make a sift or grep on paste files, there is result .  I used this fonction on my previous version and it was OK
- I tested same "simple" word on the 'search paste' box and no more result :(  sometimes Flash crashs .
- Browse important pastes looks work because there are items but it is no complete beacause some items are empty ( as mail part  or base64) 
- I tried to use the submit_paste.py script : I believe than there is an mistake on line  47 .Is the  correct syntax is  with open(file_to_submit,'rb') as f: instead  with open(file_submit,'rb') as f: ?  Another trouble,  When I use this script,  there is an error (  http  500)  .Same trouble with the webui

I'll continue to test AIL :)

Thanks

Serge

**Comment by Terrtia** [comment]
hey @tcccorp  !

Can you check if there is any error in the ``Script_AIL`` screen ? (``screen -r Script_AIL``)

**Comment by tcccorp** [comment]
Hello  Aurélien ,

There is no error message on this screen :(

Serge

**Comment by Terrtia** [comment]
Hello @tcccorp !
This issue seem to be related to ARDB
The database has been migrated from ARDB to Kvrocks.
Fixed in AIL v5.0
