### ISSUE TITLE
Double requirement given: redis

### ISSUE THREAD

**Issue by juju4** [CIRCL/AIL-framework#296]
redis twice

https://github.com/CIRCL/AIL-framework/commit/9c0a65cad87819fa171d0f6f4313d43fe420f686
```
Double requirement given: redis (from -r /var/_ail/AIL/pip3_packages_requirement.txt (line 16)) (already in redis==2.10.6 (from -r /var/_ail/AIL/pip3_packages_requirement.txt (line 5)), name='redis')
```

**Comment by Terrtia** [comment]
hey @juju4 

Thank for the report !
I removed the duplicate entry.
Should be fixed with 08661eda4e3c34c285d5d53ee95ffdf54cd1cc78
