### ISSUE TITLE
installing_deps.sh virtualenv package is missing

### ISSUE THREAD

**Issue by shaddai** [CIRCL/AIL-framework#298]
Hello,

The installing_deps.sh installs python-virtualenv package on Debian, unfortunately, the virtualenv command is installed by the "virtualenv" package. Hence it is necessary to manually install this package on a fresh Debian install in order to complete AIL installation. Replacing python-virtualenv by virtualenv in the script should do the trick to fix this ;)

**Comment by Terrtia** [comment]
Hello @shaddai !

Thank you !
Should be fix with 3051c7280f234034f2e9791660edf9df389ed2ca.

Did you run into any other issues ?

**Comment by shaddai** [comment]
Once the virtualenv package was installed, the end of the script ran well. Thanks !
