### ISSUE TITLE
Whitelisting hidden services URL?

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#309]
The hidden services crawler started to index a major p0rn website and I'd like to prevent this in the future. Is there a way to blacklist URLs (.onion) and/or to remove them from the pending ones in the queue?

**Comment by xme** [comment]
Ok, I discovered the existence of torcrawler/blacklist_onion.txt in the code :) RTFM :)
However, it blocks only domains based on 'string.tld'. The domain I needed to block was: 'fr.2ffr.2fde.2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2f2fde.2f2f2f2f2f2f2f2fes.2f2f2f2fes.2ffr.2f2f2f2f2f2f2f2f2f2f2fde.wvbs2fooveryaiwk[.]onion'.

I added this in the Crawler.py:

dom, tld = domain.split('.')[-2:]

And I'm checking the blacklist like this:

if not r_onion.sismember('blacklist_{}'.format(type_hidden_service), dom+'.'+tld):
...

**Comment by Terrtia** [comment]
hey @xme 

Thank for the report !

Should be fixed with bb301a870c822354f697db5e818bdca9b6f29bc2

**Comment by xme** [comment]
Tx! Just commited!
