### ISSUE TITLE
jquery.flot.js not found with url in var/www/update_thirdparty.sh

### ISSUE THREAD

**Issue by masatokawano** [CIRCL/AIL-framework#320]
Hi,
I have tried to install with installing_deps.sh but have got 404 error with jquery.flot.js.
I guess repository url on var/www/update_thirdparty.sh is incorrect.

AIL-framework is very helpful for me to investigate threat intelligence.

Thank you.

**Comment by th3r3d** [comment]
I change source in var/www/update_thirdparty.sh to:

#Ressource for graph
wget https://github.com/flot/flot/blob/master/source/jquery.flot.js -O ./static/js/jquery.flot.js
wget https://github.com/flot/flot/blob/master/source/jquery.flot.pie.js -O ./static/js/jquery.flot.pie.js
wget https://github.com/flot/flot/blob/master/source/jquery.flot.time.js -O ./static/js/jquery.flot.time.js
wget https://github.com/flot/flot/blob/master/source/jquery.flot.stack.js -O ./static/js/jquery.flot.stack.js

Seems work ok

**Comment by Terrtia** [comment]
hey !

Thank for the report !

I just pushed a quick fix: 423c7b14556072548c5c2feba1ba36235021b1fa

**Comment by masatokawano** [comment]
@th3r3d @Terrtia 
Thank you for quick response and fix!!
