### ISSUE TITLE
Exporting tags to TheHive

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#331]
I'm using a specific tag to export juicy stuff into a TheHive instance. 
However, some searches have multiple tags. When an alert is created in TheHive, only the tag referenced as trigger for an alert creation is added to the alert but not the remaining tags...

**Comment by xme** [comment]
I dived into the code and, apparently, observables get all tags but the alert gets only the tag that triggered...

**Comment by Terrtia** [comment]
Fixed in v5.0
