### ISSUE TITLE
Upgrade failed

### ISSUE THREAD

**Issue by timhux123** [CIRCL/AIL-framework#340]
I ran python3_upgrade.sh to upgrade my AIL server. The upgrade failed with the following error. I tried the upgrade script on 2 different servers and receive the same error.

~/AIL-framework/var/www/static/image ~/AIL-framework/var/www
--2019-04-01 16:27:51--  https://www.circl.lu/assets/images/logos/AIL.png
Resolving www.circl.lu (www.circl.lu)... 149.13.33.14, 2001:978:4200:a::14
Connecting to www.circl.lu (www.circl.lu)|149.13.33.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5700 (5.6K) [image/png]
Saving to: ‘AIL.png’

AIL.png                        100%[===================================================>]   5.57K  --.-KB/s    in 0s      

2019-04-01 16:27:52 (211 MB/s) - ‘AIL.png’ saved [5700/5700]

~/AIL-framework/var/www
./update_thirdparty.sh: line 87: ./../../AILENV/bin/activate: No such file or directory

**Comment by Terrtia** [comment]
Hi @timhux123 ,

Thank for the report !
Should be fix with 870fa1981caf6df3441980b1fa3091dd8b70c232.

Can you please try it ?

**Comment by timhux123** [comment]
Thanks for the fix!

Ran 'git pull' then 'python3_upgrade.sh' successfully.
