### ISSUE TITLE
How to use onion crawler?

### ISSUE THREAD

**Issue by jaydeepvagadiya** [CIRCL/AIL-framework#341]
I troubleshooting through document for onion crawling but i can not crawling any onion site because i don't know how to it works.

**Comment by mokaddem** [comment]
Hello,
You can find information to setup the crawling here:
https://github.com/CIRCL/AIL-framework/blob/master/HOWTO.md#tldr---local-setup

you can also find more information in these slides:
https://github.com/CIRCL/AIL-framework/blob/master/doc/presentation/ail-training-december-2018.pdf

Cheers

**Comment by jaydeepvagadiya** [comment]
But, there is not found any details about **How to use onion crawler?**

**Comment by GaganBhat** [comment]
Hey @jaydeepvagadiya , I had the same issue, are there any clear steps on how to trigger the crawler? The API says that it's a future thing planned.
