### ISSUE TITLE
Auto Installation: symbolic link error

### ISSUE THREAD

**Issue by flosada** [CIRCL/AIL-framework#35]
** file: https://github.com/CIRCL/AIL-framework/blob/master/installing_deps.sh
** line 21: test ! -L /usr/include/ft2build.h && ln -s freetype2/ft2build.h /usr/include/

+ test '!' -L /usr/include/ft2build.h
+ ln -s freetype2/ft2build.h /usr/include/

ln: failed to create symbolic link «/usr/include/ft2build.h»: File exists

**Comment by Rafiot** [comment]
Woah, totally forgot about it. Yeah, it isn't required anymore, I removed it from the install script. Thanks!
