### ISSUE TITLE
Internal Server Error Server Management

### ISSUE THREAD

**Issue by ddebast** [CIRCL/AIL-framework#353]
When I click the Server Management button I receive an Internal Server Error 
Error i noticed

<img width="1186" alt="Screen Shot 2019-05-28 at 09 03 16" src="https://user-images.githubusercontent.com/27417691/58457695-98df7600-8127-11e9-9e09-3619fec24572.png">

**Comment by Terrtia** [comment]
hey @ddebast !

It seem there is an issue with an endpoint.
Can you please git pull and restart AIL ?  

(use ``./LAUNCH -l`` to launch AIL)

**Comment by elbae** [comment]
Hi, same error here (also on /tags/).
I already did `git pull` and `./LAUNCH -l` etc .

/settings/
![image](https://user-images.githubusercontent.com/19212922/58793257-0c84f580-85f6-11e9-9312-01975cd37732.png)

![image](https://user-images.githubusercontent.com/19212922/58793206-f70fcb80-85f5-11e9-9ffb-0ce420885e06.png)

/tags/
![image](https://user-images.githubusercontent.com/19212922/58793325-2cb4b480-85f6-11e9-85f4-27ce967b49f8.png)

**Comment by gausson** [comment]
I found [https://github.com/CIRCL/AIL-framework/blob/f09bb63a358197a0a843836e536d32422b1a018c/var/www/Flask_server.py#L53](Flask_server.py#53) added hiddenServices into ignoreModule list which leads to hiddenServices module is not loaded into Flask. So Flask does not able to resolve hiddenServices blueprints.

Workaround:
Try to set `activate_crawler` in `bin/packages/config.cfg` to `True`. The template rendering works again even other configs in `Crawler` is not valid values / destinations.

Question:
I can't find any documentation about the usage of `splash_url_onion`. I assume it is a splash server that proxy to a Tor client. Contributors may briefly explain how it works.

**Comment by Terrtia** [comment]
Hey !

@gausson  Nice catch ! This is an old feature used by all bootstap 3 templates (bug introduced by the bootstrap 4 migration). 

Fixed with 9cb6312


The purpose of [this guide](https://github.com/CIRCL/AIL-framework/blob/master/HOWTO.md#crawler) is to describe how to install/setup the crawler.

You right, we need to have a complete documentation to explain how the crawler work. I will add it in the next few days (1 or 2 days).

The ``splash_url_onion`` is used if you want to use a remote Splash server.

**Comment by elbae** [comment]
> I found [Flask_server.py Line 53](https://github.com/CIRCL/AIL-framework/blob/f09bb63a358197a0a843836e536d32422b1a018c/var/www/Flask_server.py#L53) added hiddenServices into ignoreModule list which leads to hiddenServices module is not loaded into Flask. So Flask does not able to resolve hiddenServices blueprints.
> 
> Workaround:
> Try to set `activate_crawler` in `bin/packages/config.cfg` to `True`. The template rendering works again even other configs in `Crawler` is not valid values / destinations.
> 
> Possible Solution:
> Add a condition checking wrapping the url rendering about hiddenServices in all templates
> 
> Question:
> I can't find any documentation about the usage of `splash_url_onion`. I assume it is a splash server that proxy to a Tor client. Contributors may briefly explain how it works.
> 
> Update:
> May be [this setup guide](https://github.com/CIRCL/AIL-framework/blob/master/HOWTO.md#crawler) is talking about how to setup `Crawler` correctly

This solves the problem for me.
Now, it's not clear why with a new installation the /settings/ link does not exists anymore:
![image](https://user-images.githubusercontent.com/19212922/59596456-04e64600-90f8-11e9-9d4a-f2a84d01b709.png)

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
