### ISSUE TITLE
ARDB not ready / Connection refused

### ISSUE THREAD

**Issue by emilioluco** [CIRCL/AIL-framework#354]
Hi there.

I made a fresh Ubuntu 16.04.6 installation just for AIL-Framework but whenever I try to run (./LAUNCH.sh choosing 1, 2, 3, 4, 5, 6 options) I've got the error shown in image.

Is there any "correct" order (Redis, Ardb, Logs, Queues, Scripts, Flask) to launch AIL?

Thanks.

![1](https://user-images.githubusercontent.com/49241788/58818723-ea46a400-8604-11e9-9693-7053c5fdf3d8.png)

**Comment by Anderson0abr** [comment]
Hi, you can automatically run every service with `./LAUNCH.sh -l` to make it quicker.
As for the ARDB error, it takes some time to start, so it's normal to keep seeing this messages. Just wait a little bit and it should start.

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
