### ISSUE TITLE
Error starting Flask_server

### ISSUE THREAD

**Issue by Anderson0abr** [CIRCL/AIL-framework#355]
Hi, my AIL instance got some stuck queues these days so I tried to restart it with 
`./bin/LAUNCH.sh -k && ./bin/LAUNCH.sh -l`
After that the Flask_server couldn't start. Other services are running normally.
I managed to traceback the error to the "Flask_Tags" import, but I couldn't understand the exact reason to the crash or the solution.

Error shown in the Flask_server screen:
```
  File "/home/xxx/AIL-framework/AILENV/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "modules/Tags/Flask_Tags.py", line 36, in <module>
    clusters = Clusters(skip_duplicates=True)
  File "/home/xxx/AIL-framework/AILENV/lib/python3.6/site-packages/pymispgalaxies/api.py", line 272, in __init__
    clusters.append(json.load(f))
  File "/usr/lib/python3.6/json/__init__.py", line 296, in load
    return loads(fp.read(),
  File "/home/xxx/AIL-framework//AILENV/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 66188: ordinal not in range(128)

```

**Comment by Anderson0abr** [comment]
Digging up a little bit I found out that:

1. File_Tags import pymispgalaxies Clusters;
2. Clusters' `__init__()` appends a `json.load()`;
3. `json.load()` receives a `fp.read()` parameter;
4. At some point `fp.read()` reads `AIL-framework/AILENV/lib/python3.6/site-packages/pymispgalaxies/data/misp-galaxy/clusters/mitre-enterprise-attack-malware.json`;
5. At line 1714 there's a description line with the following description:
`NETEAGLE is a backdoor developed by APT30 with compile dates as early as 2008. It has two main variants known as “Scout” and “Norton.” (Citation: FireEye APT30) Aliases: NETEAGLE`.;
6. The error occurs when trying to read the quotes around Scout and Norton.

**Comment by Terrtia** [comment]
hi @Anderson0abr !

This may be related to #321

On my machine with python3, this is what I get:

```
In [1]: import locale

In [2]: locale.getpreferredencoding(False)
Out[2]: 'UTF-8'

In [3]: locale.getpreferredencoding()
Out[3]: 'UTF-8'
```

Does it return ASCII for you?

**Comment by Anderson0abr** [comment]
Hi @Terrtia !

It returns 'ANSI_X3.4-1968'.

**Comment by Anderson0abr** [comment]
I checked the solution on  #321 , but my LANG env is already en_US.UTF-8

**Comment by Terrtia** [comment]
This is weird. Can you paste the output of the following command:
```
$ locale 
```

**Comment by Anderson0abr** [comment]
Sure

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=pt_BR.UTF-8
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME=pt_BR.UTF-8
LC_ADDRESS=pt_BR.UTF-8
LC_TELEPHONE=pt_BR.UTF-8
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION=pt_BR.UTF-8
LC_ALL=

**Comment by Terrtia** [comment]
The LC_CTYPE and LC_ALL errors are really weird

Try the following command:

```
$ sudo locale-gen "en_US.UTF-8"
```

```
$ sudo dpkg-reconfigure locales
```

**Comment by Anderson0abr** [comment]
`$ sudo locale-gen "en_US.UTF-8"` solved the problem.
Still don't understand why it happened so sudden though.. but for now that's good enough.

Thank you very very much @Terrtia !

**Comment by Terrtia** [comment]
Excellent, thank you for the feedback !

**Comment by mohlcyber** [comment]
Hi Guys,
i ran into the same issue. Complete fresh install on Debian9.4. Nothing really helped. Same pymispgalaxies api.py issue as mentioned above. It is definitely an issue with the locales.

Maybe someone else will run into this i did the following to fix it.:

`vim.tiny /etc/environment`

And pasted the following two lines:
`LANG=en_US.utf-8`
`LC_ALL=en_US.utf-8`

Restart and done. Maybe can help others.
