### ISSUE TITLE
Multiple tags & TheHive?

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#357]
I'm exporting events from AIL into TheHive. To achieve this, I created a specific tag.
Some events are tagged multiple times (the specific tag for TheHive + others related to the content).

When the alert is created in TheHive, only the specific tag is created but not the others? Is it on purpose or a bug?

/x

**Comment by Terrtia** [comment]
Hey @xme !

An alert in the hive is created when your specific tags is triggered on an item. But we don't know if this item is still being processed by some modules. 

I can add the others tags but some might be missing.

I opened a new issue to track the process status: #358

**Comment by xme** [comment]
Ack! But the alerts I'm creating in TheHive are coming from the "Terms Management" module (I track several regexes). So, the tags are applied at the same time (match regex 'x' -> tags are this, this and this.

**Comment by Terrtia** [comment]
I pushed a fix: e65f465f02a6799babad87094fa92bba806d835c

But some tags might be missing (item still processed by other modules)

There is also another issue: duplicate alerts.
If multiple tags are triggered on the same item, an alert is created for each tracked tags.
