### ISSUE TITLE
Crawler and Website

### ISSUE THREAD

**Issue by Malwar3Ninja** [CIRCL/AIL-framework#362]
Hi Team, 

I have been able to setup the tool but facing some errors. The setup was done without errors, the app is working, pystemon feeds are working and I can see it in AIL. The problem which I am facing is:
a. On accessing the /settings page there is a 500 Internal Server Error
b. The crawlers are not working at all. I have setup the crawlers using https://github.com/CIRCL/AIL-framework/blob/master/HOWTO.md.  (No steps changed)
c. the command LAUNCH.sh -l dosnt work in my scenario so I have to start AIL manually using ./LAUNCH.sh and then press options from 1-6

Please help me resolve all three problems. I am using the latest master cloned yesterday. 

Error from Screen: Crawler

![image](https://user-images.githubusercontent.com/34618086/60865510-c0fae280-a258-11e9-9ddb-8038449905e8.png)

OS Details: Debian

Thanks

**Comment by Terrtia** [comment]
Hey @Malwar3Ninja !

Thank for the report !

Can you please copy/paste the ``Flask_AIL`` screen error output ?

Do you have any errors with the ``LAUNCH.sh -l`` command ?

**Comment by Malwar3Ninja** [comment]
Hi, 

Output of Flask_AIL

FLASK_AIL
![image](https://user-images.githubusercontent.com/34618086/60869766-2901f680-a262-11e9-866e-4ba404c9d80c.png)


Launch.sh -l Output:

![image](https://user-images.githubusercontent.com/34618086/60869870-5ea6df80-a262-11e9-8771-e46d9f563f4d.png)

**Comment by Malwar3Ninja** [comment]
I am using Python 3.4, do you think that can be a problem ?

**Comment by Terrtia** [comment]
You right, I just added the minimal python requirement in the README  57c42cf7996fab26f77f2c2fbc0e2d8712bca9ab

[subprocess.run()](https://docs.python.org/3/library/subprocess.html#subprocess.run) was added in Python 3.5  

Can you update to 3.5 or higher ?

**Comment by Malwar3Ninja** [comment]
Sure,I can check

**Comment by Malwar3Ninja** [comment]
Upgrading the firmware to Python 3.5 is solving the web page related problems. But the crawler is still throwing the same error. 

Update:
Post upgrading to Python 3.5
- ./LAUNCH.sh is working
- Web page /settings/ is working
- Crawler is not working yet

[ Error from Crawler Screen]

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/configparser.py", line 786, in get
    value = d[option]
  File "/root/AIL-framework/AILENV/lib/python3.6/collections/__init__.py", line 882, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/root/AIL-framework/AILENV/lib/python3.6/collections/__init__.py", line 874, in __missing__
    raise KeyError(key)
KeyError: 'splash_url_onion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./Crawler.py", line 319, in <module>
    splash_url = '{}:{}'.format( p.config.get("Crawler", "splash_url_onion"),  splash_port)
  File "/usr/local/lib/python3.6/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'splash_url_onion' in section: 'Crawler'

**Comment by Malwar3Ninja** [comment]
on attaching screen to docker terminal, I can see an error
"docker: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU cfs period/quota or the cgroup is not mounted.
See 'docker run --help'.
"
I am not sure how to resolve this, can you help ?

**Comment by Terrtia** [comment]
``splash_url_onion`` was renamed  as ``splash_url``

Should be fixed with 26a4c7fd2c2bd438c1a605730cca7431f58608b7

Let me know if this solve your issue

**Comment by Malwar3Ninja** [comment]
This worked! 

I faced another problem, my docker screen was giving some error related to "failed to allocate nano cpu " so I removed the --cpus=1 flag from the crawler launching script. 

Its soved now.! Thanks
