### ISSUE TITLE
/usr/bin/ld: cannot find -lsnappy

### ISSUE THREAD

**Issue by cudeso** [CIRCL/AIL-framework#37]
Installing on an updated Ubuntu 14.04 and getting this error when running installing_deps.sh

```
+ make
cd src && make all
make[1]: Entering directory `/data/AIL-framework/redis-leveldb/src'
g++ rl_util.o rl_server.o rl_connection.o rl.o rl_request.o rl_kv.o rl_set.o rl_hash.o rl_list.o ../vendor/libleveldb.a  ../vendor/libleveldb.a -lm -L/usr/lib -lev -L/usr/lib -lgmp -lsnappy -lpthread -o ../redis-leveldb
/usr/bin/ld: cannot find -lsnappy
collect2: error: ld returned 1 exit status
make[1]: *** [redis-leveldb] Error 1
make[1]: Leaving directory `/data/AIL-framework/redis-leveldb/src'
make: *** [all] Error 2
```

"libsnappy1" is installed.

Ran the installing_deps.sh script also after following the manual installation steps but no luck either.

**Comment by cudeso** [comment]
Continued a couple of steps by adding libsnappy-dev dependency. 
See https://github.com/CIRCL/AIL-framework/pull/38

Not entirely there yet for getting AIL up and running but coming closer ;-)

**Comment by adulau** [comment]
Interesting and there was a related issue when linking redis-leveldb but this should have been solved in redis-leveldb https://github.com/KDr2/redis-leveldb/issues/14 . Let me know if there is still issue.

**Comment by adulau** [comment]
I suppose the issue was solved. Feel free reopen if this is not the case.
