### ISSUE TITLE
Install/Inital Issues

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#375]
Hi
I think I'm missing something here. I thought I'd have a look at this so Ive created a ubuntu 18.04 server, run the install_deps.sh script... no issues.
I can see port 7000 is listening, but when I try to goto port 7000... nothing.
I can see there are a load of screens created, i can reattach to them,cat see any errors

Ive also tested on a ubuntu desktop version, and exactly the same. 
What am I missing?

**Comment by Terrtia** [comment]
hi @Phil-ThePower-Pearce !

Can you access the UI via https ? https://localhost:7000

**Comment by Phil-ThePower-Pearce** [comment]
No nothing, I can see the port listening. I can see in the flask screen theres no errors.

**Comment by Terrtia** [comment]
We can check if the API work:
```bash
. ./AILENV/bin/activate
cd tests
python3 testApi.py
```

**Comment by Phil-ThePower-Pearce** [comment]
I followed your commands to the letter

**Comment by Terrtia** [comment]
Do you have a directory named ``AILENV`` in the ``AIL-framework`` directory ?

If you got one, we can re-export all the variables:

```bash
cd AIL-framework
echo export AIL_HOME=$(pwd) >> ./AILENV/bin/activate
echo export AIL_BIN=$(pwd)/bin/ >> ./AILENV/bin/activate
echo export AIL_FLASK=$(pwd)/var/www/ >> ./AILENV/bin/activate
echo export AIL_REDIS=$(pwd)/redis/src/ >> ./AILENV/bin/activate
echo export AIL_ARDB=$(pwd)/ardb/src/ >> ./AILENV/bin/activate
```

Please let me know if this solve your issue.
If this doesn't work, I can create a new diagnostic script .

**Comment by Phil-ThePower-Pearce** [comment]
I had installed to /opt/
I reinstalled to the user home directory and it all started working
