### ISSUE TITLE
Please make sure you have a AIL-framework environment, au revoir

### ISSUE THREAD

**Issue by psychomad** [CIRCL/AIL-framework#376]
Hi
maybe is just something that i miss but after followed all instruction to install when i do:

./LAUNCH -l

i get : Please make sure you have a AIL-framework environment, au revoir

I crawling a little try to find the cause but no clue..

This happen on Kali linux 2019-2

**Comment by Terrtia** [comment]
Hi @psychomad !

Did you encounter any issues with the installation ?

Do you have a directory named ``AILENV`` and a file named ``DEFAULT_PASSWORD`` ?

**Comment by psychomad** [comment]
Hello
Sorry for delay i was around the world.
No issue during the installation but no AILENV dir in my distro.

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.

**Comment by viyeskolo** [comment]
> It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.

Hi, I've just installed today and I also get same issue constantly, I also don't have those directories

**Comment by alikat500** [comment]
I see the same issue after a fresh install. The install finished with an error though:
...
make[1]: Leaving directory '/home/<snipped>/ail-framework/ardb/src'
~/ail-framework
ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'


OS version: Ubuntu 20.04.2 LTS

**Comment by Yuriassisx** [comment]
I'm having the same problem when running the launch

**Comment by Maurycyl** [comment]
How to fix it?

**Comment by cdhunterhacker** [comment]
i tried twice today - same issue.  Those 2 directories not present.

**Comment by Terrtia** [comment]
Hi @cdhunterhacker !
The installer is creating the virtualenv. If you can't find the AIELENV in the ail-framework directory, the installer exited with an error.
Can you check /pastethe output of the installer ?

**Comment by sidh104** [comment]
Facing same error. can anyone help out how to exactly run this installation with steps
