### ISSUE TITLE
Internal server error when manually submitting paste

### ISSUE THREAD

**Issue by robertnixon2003** [CIRCL/AIL-framework#377]
When I try to submit a paste through the UI I get an error
![image](https://user-images.githubusercontent.com/20773170/64084585-f3760880-ccfa-11e9-88a2-e71b93474c24.png)

No error log written.

Nothing in the module manager but and invalid PID

![image](https://user-images.githubusercontent.com/20773170/64084620-3b952b00-ccfb-11e9-8d0e-785a9d66cb51.png)

**Comment by robertnixon2003** [comment]
crawler and submit_paste say they are not running. I started the crawler right after I start AIL.

![image](https://user-images.githubusercontent.com/20773170/64084645-7a2ae580-ccfb-11e9-9045-2cafca0c87cb.png)

**Comment by Terrtia** [comment]
Hi @robertnixon2003 !

Can you please check the output of the Flask server via ``screen -r AIL_FLASK`` ?

**Comment by robertnixon2003** [comment]
Yep here you go:
```
(AILENV) root@app1:/opt/AIL-framework# screen -r AIL_FLASK
There is no screen to be resumed matching AIL_FLASK.
```

**Comment by Terrtia** [comment]
Sorry, I made a typo, can you please check the output of: ``screen -r Flask_AIL`` ?

**Comment by robertnixon2003** [comment]
```
root@app1:/opt/AIL-framework# screen -r Flask_AIL
There is a screen on:
        31821.Flask_AIL (09/02/2019 12:50:25 AM)        (Attached)
There is no screen to be resumed matching Flask_AIL.
```

**Comment by robertnixon2003** [comment]
Also the web interface is slow and sometimes stops responding. Are there recommended hardware requirements and OS suggestions? Running Ubuntu 18.04 right now. 8 core/32 GB RAM.

**Comment by robertnixon2003** [comment]
I got the manual paste submit to work but the UI becomes unresponsive. Also Chrome does not trust it since it is using a self signed cert. Also gives an error about scrambled credentials.

**Comment by robertnixon2003** [comment]
I updated the DNS for web in bin/packages/config.cfg and that seemed to have sped up the UI

**Comment by robertnixon2003** [comment]
Why is this set to that IP?


bin/packages/config.cfg
[Web]
dns = 149.13.33.69

**Comment by Terrtia** [comment]
> ```
> root@app1:/opt/AIL-framework# screen -r Flask_AIL
> There is a screen on:
>         31821.Flask_AIL (09/02/2019 12:50:25 AM)        (Attached)
> There is no screen to be resumed matching Flask_AIL.
> ```

The session is still attached on another terminal. You can get the ouput of the Flask server with:
``screen -r -d -S Flask_AIL``


You can also test to submit a paste via the API: https://github.com/CIRCL/AIL-framework/blob/master/doc/README.md#import_item


> Also the web interface is slow and sometimes stops responding. Are there recommended hardware requirements and OS suggestions? Running Ubuntu 18.04 right now. 8 core/32 GB RAM.

It really depends of the volume of processes items (Pastes, crawled websites).
The minimal requirement is 8 cores and 16GB of RAM.



> I got the manual paste submit to work but the UI becomes unresponsive. Also Chrome does not trust it since it is using a self signed cert. Also gives an error about scrambled credentials.

The certificate is auto-generated and located in: ``var/www/servert.crt``, you can replace it or add an exception in your browser. 




> I updated the DNS for web in bin/packages/config.cfg and that seemed to have sped up the UI
> Why is this set to that IP?
> 
> bin/packages/config.cfg
> [Web]
> dns = 149.13.33.69

This field is not used anymore. This IP was related to [BGP-Ranking](https://github.com/D4-project/BGP-Ranking)

**Comment by robertnixon2003** [comment]
Thanks I am in the middle of a reinstall. I am closing this issue as it seems like it is user error.
