### ISSUE TITLE
KeyError: 'AIL_BIN'

### ISSUE THREAD

**Issue by jasmith1338** [CIRCL/AIL-framework#388]
I have been getting the following issue,
not having much luck resolving it. any idea?
trying to run this from a screen session in the background.
:~/AIL-framework/bin/feeder# python3 pystemon-feeder.py
Traceback (most recent call last):
  File "pystemon-feeder.py", line 30, in <module>
    configfile = os.path.join(os.environ['AIL_BIN'], 'packages/config.cfg')
  File "/usr/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'AIL_BIN'
root@ubuntu-s-3vcpu-1gb-tor1-01:~/AIL-framework/bin/feeder#

**Comment by Terrtia** [comment]
hey @jasmith1338 !

You need to run this script inside the virtual environment.

You can activate it with the following command:

```
cd AIL-framework
. ./AILENV/bin/activate
```

**Comment by jasmith1338** [comment]
still getting the same error after I run that command then try to rerun pystemon-feeder.py

**Comment by Terrtia** [comment]
It should be fixed in the recent version of AIL. Feel free to reopen if this is not case.
