### ISSUE TITLE
Exception in Wordtrending section ([Errno32] Broken pipe)

### ISSUE THREAD

**Issue by JerThi** [CIRCL/AIL-framework#39]
I have an error that doesn't allow the framework to work correctly 
While browsing the Wordtrending section, the "Broken Pipe" error , illustrated below, is emerging:

![wordtrending](https://cloud.githubusercontent.com/assets/13851742/9358379/00c01174-468c-11e5-9830-14fcd1656e4c.png)

Could you help please .
Is it because I'm using a VM on my personnal computer ?

**Comment by adulau** [comment]
Looks like a permission problem to create the CSV file used by the Wordtrending? Could check the perms. 

Let me know.

**Comment by JerThi** [comment]
Actually, the wordstrendingdata.csv file is created and feed with the "first" datas. 
Could it be locked after its first creation ?

**Comment by JerThi** [comment]
Moreover, it seems that the all first lauching worked perfectly for the Dashboard part as well.
But know, I have problems regarding the table on the left and the main charts : they are not displayed anymore

**Comment by adulau** [comment]
Have you checked all the GNU screen session and their respective output?

**Comment by SteveClement** [comment]
@JerThi in case this is still of interest, let us know.
