### ISSUE TITLE
Tracked terms are gone?

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#395]
Hello,
I upgraded to 2.2 (automatic via "LAUNCH.sh -l"... but now I can't find all the words and regex that I created... Any idea?

**Comment by Terrtia** [comment]
Hi @xme ,

All word/set/regex are converted to the new format.
Only invalid term are not converted:
- word and set of words that contain one of the following characters [<>~!?@#$%^&*|()_-+={}":;,.' ]/\ 
- invalid python regex

You can find a list of all valid/invalid tracked term in the update output

**Comment by xme** [comment]
Hmmm... I should have missed this... It is logged somewhere?

**Comment by xme** [comment]
Another question: for regex, do I need to add the "/"?
Ex: "/test\.com/" or "test\.com" is ok
Both are accepted by AIL.

**Comment by Terrtia** [comment]
It is not logged anywhere... (we need to log all the update by default)

The old regex format is not used anymore (you don't need to add the "/"). 
You can enter any valid python [regex](https://docs.python.org/3/library/re.html)

Ex: 
- term to track: test.com
- regex: test\\.com

**Comment by xme** [comment]
Tx for the feedback. I recreated my searches manually... :)
