### ISSUE TITLE
Relative URL issue with the login page

### ISSUE THREAD

**Issue by be-mot** [CIRCL/AIL-framework#403]
Hi,

In follow-up of #236 , I tested the new master after the solution for that one was merged.

I noticed that with regards to the relative url the login-page seems to ignore the setting.

When I try to connect with http://ail-server/ail (as baseUrl = /ail in the config), the app redirects me to /login instead of the expected /ail/login .

After the login is redirects correctly to /ail/

I tried to see how the baseUrl can be added to Flask login manager but didn't manage to figure it out.

**Comment by Terrtia** [comment]
Hey @be-mot !
Thank you for the report,
Should be fixed with  9051c40

Can you please check if you have any issue with another endpoint ?

**Comment by be-mot** [comment]
Hey,

We didn't encounter another issue since.
This one can be closed, if we find something else I'll open a new issue.

Thanks a lot for your help !

**Comment by Terrtia** [comment]
hey @be-mot !

Thank you for the feedback !
