### ISSUE TITLE
Dashboard graphs and logs disapear when switching to the Words Trending tab.

### ISSUE THREAD

**Issue by Beercow** [CIRCL/AIL-framework#41]
When I switch over to the Words Trending tab and then go back to the Dashboard, all of the data that use to be in the Dashboard is reset. Also, if the browser is closed, all of the Dashboard data is lost.

**Comment by adulau** [comment]
Thank you for the report.

Indeed, this is a current limitation in the AIL front-end. The alerting logging is used to keep the logging but the front-end display only display the currently processed feed. We might add this feature in an updated version.
