### ISSUE TITLE
DEFAULT_PASSWORD not found

### ISSUE THREAD

**Issue by Anderson0abr** [CIRCL/AIL-framework#410]
Hi,

I updated AIL from an older version (v1.8 i guess..) and now there's a authentication page (that's awesome btw). I read that the default password should be in a DEFAULT_PASSWORD file, but I can't find it! Maybe it wasn't created.. or maybe I just couldn't find it. Where should it be?

Regards,

**Comment by Terrtia** [comment]
HI @Anderson0abr 

This file is located in the `AIL-framework` directory.

You can create a new one if you don't find it.

```bash
cd AIL-framework
. ./AILENV/bin/activate
cd bin/
./LAUNCH -lrv
./LAUNCH -lav
cd ..
cd var/www/
./create_default_user.py
```
(The admin@admin.test password is also printed in the console output)

**Comment by Anderson0abr** [comment]
Thank you @Terrtia ! It worked perfectly.
