### ISSUE TITLE
Internal server error and ARDB killed

### ISSUE THREAD

**Issue by sunil3590** [CIRCL/AIL-framework#415]
When I try to log in
![image](https://user-images.githubusercontent.com/839421/67284885-19967880-f4f4-11e9-9106-cd56a51ca84e.png)

Flask logs
![image](https://user-images.githubusercontent.com/839421/67284964-42b70900-f4f4-11e9-881f-d4e169434ff2.png)

ARDB logs
![image](https://user-images.githubusercontent.com/839421/67285001-57939c80-f4f4-11e9-80ff-4e081d8b6a7e.png)

When I run `./LAUNCH.sh -k` after seeing the above errors
![image](https://user-images.githubusercontent.com/839421/67284843-01bef480-f4f4-11e9-9b49-c8936957823a.png)

I read #224 but couldn't figure out what the problem is. I've been able to login and view various pages a few days back.

**Comment by sunil3590** [comment]
When I try `./LAUNCH.sh -l`
![image](https://user-images.githubusercontent.com/839421/67285430-2d8eaa00-f4f5-11e9-9063-41b6abda8606.png)

**Comment by Terrtia** [comment]
Fixed in v50
