### ISSUE TITLE
Question: Disable storing ONION screenshots.

### ISSUE THREAD

**Issue by ttuuxxeerr** [CIRCL/AIL-framework#420]
Hi there,
I would like to know if there is a way to keep using the Onion crawler feature without storing the onion screenshots.  I am worry to enable this option and store not appropriate content in my server. 

Thanks in advance for your advice.

**Comment by Terrtia** [comment]
Hi @ttuuxxeerr !

You can change the default behavior of the crawler in ``configs/core.cfg`` (if you are using the lastest realease).

You need to set ``default_crawler_png`` to false in the ``[Crawler]`` section

**Comment by ttuuxxeerr** [comment]
Great! I will test it. Thanks

**Comment by ttuuxxeerr** [comment]
thanks it is working
