### ISSUE TITLE
Edit graph words. 

### ISSUE THREAD

**Issue by Beercow** [CIRCL/AIL-framework#43]
In the words trending tab, edit word list does not work. If it is clicked on, nothing happens.

**Comment by Beercow** [comment]
Anyone have a suggestion as to why this doesn't work?

**Comment by SteveClement** [comment]
Bug is confirmed. Will see with @Starow perhaps.

**Comment by Starow** [comment]
Hard to tell because I don't have the GUI under my eyes anymore but actually I don't remember that I code some web feature able to modify the word list "on the fly".
I'm pretty sure that the word list file needed to be edited by hand. :/

**Comment by adulau** [comment]
This has been significantly improved in the recent version of AIL including dynamic term frequency with a term list that can be managed. Feel free to test the latest version and reopen if the issue is still applicable. Thank you.
