### ISSUE TITLE
What's the correct AIL config files?

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#444]
I'm trying to split my DNS traffic depending on the module and different than the one configured at OS level. Previously, I had a .cfg file in /bin//packages with entries like 'dns = xxx' for DomClassifier, Mail etc...It seems that this config is not present anymore!?
What's the best way to configure proper DNS servers?

**Comment by Terrtia** [comment]
Hi @xme !

We moved ``bin/packages/config.cfg`` to ``configs/core.cfg``. 
(This file haven't changed)

**Comment by xme** [comment]
Tx! :)
