### ISSUE TITLE
Terms top plot, internal server error

### ISSUE THREAD

**Issue by robertnixon2003** [CIRCL/AIL-framework#445]
Whenever I go to the Terms top plot I get Internal Server Error. There is no error in the Script Error Log.

https://localhost:7000/terms_plot_top/

![image](https://user-images.githubusercontent.com/20773170/71360314-6da5f380-255d-11ea-91a6-29afa6b53000.png)

**Comment by Terrtia** [comment]
Hi @robertnixon2003,

This endpoint is deprecated,
Fixed with 91ce045d914487521dfe9459519be40303f12e8a
