### ISSUE TITLE
Trending Charts are blank

### ISSUE THREAD

**Issue by robertnixon2003** [CIRCL/AIL-framework#446]
Every chart on the trending charts page is blank. https://localhost:7000/trending/

No error in the logs and AIL has been running for a week with the AIL feed coming in.

![image](https://user-images.githubusercontent.com/20773170/71360339-8dd5b280-255d-11ea-9674-b662fbb5399c.png)

**Comment by Terrtia** [comment]
Hi @robertnixon2003,

Thanks for the report !
All the trending charts have been removed from AIL (DB performance)

Should be fixed with 91ce045
