### ISSUE TITLE
LUHN check on credit cards

### ISSUE THREAD

**Issue by syloktools** [CIRCL/AIL-framework#447]
Can a luhn check be added to validate credit card numbers?

https://pypi.org/project/fast-luhn/

**Comment by adulau** [comment]
I thought we do it there https://github.com/CIRCL/AIL-framework/blob/ecd14b91d95af3960c56719a8227ffc5ddd5e4ff/bin/CreditCards.py#L68 

Do you have any specific issues?

**Comment by robertnixon2003** [comment]
I have seen some invalid card such as 4777777777777777

**Comment by Terrtia** [comment]
Hi @robertnixon2003 !

I did some test and didn't find any issue with your Luhn implementation,
``4777777777777777`` is not detected as a valid credit-card

Can you share a sample of one of your false positive ?
