### ISSUE TITLE
Remove from Queue

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#458]
Hi,
How do you remove something from a queue?
Got SPLASH DOWN from some reason and its just repeating.

Thanks

Also how do you become a collaborator? its in the readme, but no details on how to sort out.

**Comment by Terrtia** [comment]
Hi @Phil-ThePower-Pearce !

You need to kill and restart all SPLASH dockers:
  - ``sudo docker ps``
  - ``sudo docker kill <splash_docker_id>``
  - relauch all splash dockers

related: #425 

you right, we should add a section in the README.

If you are interested to contribute to AIL, there are many ways to contribute and participate to the project.

Feel free to fork the code, play with it, make some patches/documentation and send us the pull requests.
