### ISSUE TITLE
Script_AIL

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#460]
Hi,
Ive launched the script with the -l , now when I go through each screen to check everythings working. I see in the SCRIPT_AIL screen

`Traceback (most recent call last):
  File "./IPAddress.py", line 64, in <module>
    ip_networks.append(IPv4Network(network))
  File "/usr/lib/python3.6/ipaddress.py", line 1511, in __init__
    addr = self._ip_int_from_string(args[0])
  File "/usr/lib/python3.6/ipaddress.py", line 1114, in _ip_int_from_string
    raise AddressValueError('Address cannot be empty')
ipaddress.AddressValueError: Address cannot be empty
`
I did a search of closed issues, but couldnt find anything.  
Nothing is appearing in the logs

Any ideas?

**Comment by Phil-ThePower-Pearce** [comment]
I got past this by adding in an IP in the core.cfg

**Comment by Terrtia** [comment]
Hi @Phil-ThePower-Pearce 
Thank you for the report !

Fixed with 8770bf05d732afe3a48cb03cd2b463c73bd8c061
