### ISSUE TITLE
ModuleInformation

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#466]
As soon as I run the module information from the scripts screen, all the queues  in the gui dissapear to "no feeds" after a while they disappear and appear, but previously all queues we present on the screen.

When I goto start a stuck queue:

bash: ./SentimentAnalysis.py: No such file or directory
bash: ./Web.py: No such file or directory

**Comment by Terrtia** [comment]
Fixed in v5.0
