### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by Phil-ThePower-Pearce** [CIRCL/AIL-framework#469]
Hi,
Im using AWS ses for email notifications
Ive added the details in the core.cfg but constantly get this when testing

`  File "/home/ubuntu/Apps/AIL-framework/bin/NotificationHelper.py", line 46, in sendEmailNotification
    smtp_server = smtplib.SMTP(sender_host, sender_port)
  File "/usr/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
`

I can recieve emails using the aws console test email....

**Comment by Terrtia** [comment]
Hi @Phil-ThePower-Pearce !

Can you please give me the complete stack traceback ?

**Comment by Phil-ThePower-Pearce** [comment]
^^ No problem. What do you need me to run?

**Comment by Terrtia** [comment]
Can you create a term tracker with an email address and trigger it ? (submit something with PasteSubmit)
You should have a traceback in the TermTrackerMod or RegexTracker module output.

**Comment by Terrtia** [comment]
Fixed in v5.0
