### ISSUE TITLE
Feeding maxing out at 150 pastes per minute when importing

### ISSUE THREAD

**Issue by src7** [CIRCL/AIL-framework#477]
Hello,

why can't we feed more than 150 pastes per minute ?
It doesn't look like a hardware bottleneck.

**Comment by v1psta** [comment]
I am feeding more then 150 pastes a minute....

**Comment by src7** [comment]
Thank you, we tried on different servers and `Processed pastes` is stuck at about 150 (on one single feeder, using `bin/import_dir.py`)

**Comment by v1psta** [comment]
I will reach out to my team, and see if they had to make any special
changes.

**Comment by src7** [comment]
Thank you, currently I am trying something with `configs/6382.conf`

**Comment by Terrtia** [comment]
Hi @src7 !
Do you have any stuck queues ?
Are you processing huge files ?

It might be a disk issue. We create the ``Global`` module to save all items on disk.
Can you try to launch multiple  ``Global`` modules ?:

```bash
Screen -r Script_AIL
```

 ``Crtl+a c``

```bash
. ./AILENV/bin/activate
cd bin
./Global.py
```

**Comment by src7** [comment]
Hi,

Queues are not empty, but not stuck.
Files processed are regular pastes from pastebin.

The disk is NVME or RAM based (direct I/O disabled for the last one).

I will try theses commands.

The weird thing is that it is the same constant rate all the time.
Could it be one sleep somewhere ? (didn't found it yet)

We compile the last version of AIL directly from the master branch on a fresh install Ubuntu Bionic.

**Comment by src7** [comment]
Imported pastes are not compressed (if it can help)

**Comment by mokaddem** [comment]
@src7 Are you using the `import_dir.py` script by any chance?
If yes, you might want to change the sleep time to something smaller. Look at this:
https://github.com/CIRCL/AIL-framework/blob/5ae22ec2168a55e89279228de7c4cdbbd36baa44/bin/import_dir.py#L114

**Comment by src7** [comment]
Yes, and that is not the problem. I see way more than 150 pastes per minute imported in the console (no sleep set).

**Comment by mokaddem** [comment]
1. In which console do you see that more than 150? ``Global``, ``Mixer`` or ``import_dir? By default ``args.seconds`` is set to 0.2s
2. And where do you see the 150 pastes per minute?

**Comment by src7** [comment]
1. import_dir (also tested with different sleep values and even without the sleep line)
2. In the Web Dashboard, Processed pastes

**Comment by src7** [comment]
After some research I have found that tuning this delay change everything :

https://github.com/CIRCL/AIL-framework/blob/b4a85c0e9808c1660adc36400e33238121099f4d/bin/Helper.py#L105

**Comment by Terrtia** [comment]
Good catch !
I did some modification on the ZMQ feeders. 998f8cc8e15f81dff5a4d006509d5c58883da629
The feeder use ZMQ Poller for more general non-blocking I/O.
 
You should reach more than 4000 pastes per minute
