### ISSUE TITLE
Upgrade breaks dependencies?

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#494]
I upgraded and restarted my AIL instance, not I'm seeing this from the Crawler:

```
Launching Crawler: http://xxxxxxxxxxx.onion
Traceback (most recent call last):
  File "./torcrawler/tor_crawler.py", line 8, in <module>
    from TorSplashCrawler import TorSplashCrawler
  File "/opt/AIL-framework/bin/torcrawler/TorSplashCrawler.py", line 14, in <module>
    from scrapy.spidermiddlewares.httperror import HttpError
ModuleNotFoundError: No module named 'scrapy'
b''
```

Any idea?

**Comment by xme** [comment]
Manually installed

- scrapy
- scrapy_splash

Looks to be working now...

**Comment by Terrtia** [comment]
Hi @xme !

This is indeed really weird.
I added them in the default requirement (and reinstall them in the [v3.1](https://github.com/ail-project/ail-framework/releases/tag/v3.1) update) to avoid this kind of issue.
