### ISSUE TITLE
Rocksdb installing issue

### ISSUE THREAD

**Issue by Azrara** [CIRCL/AIL-framework#499]
Hello I'm trying to install AIL on a Linux machine and I'm getting these errors linked to rocksdb:

 error: implicitly-declared ‘constexpr rocksdb::FileDescriptor::FileDescriptor(const rocksdb::FileDescriptor&)’ is deprecated [-Werror=deprecated-copy]
  157 |         largest_key(_largest_key) {}

error: implicitly-declared ‘constexpr rocksdb::FileDescriptor::FileDescriptor(const rocksdb::FileDescriptor&)’ is deprecated [-Werror=deprecated-copy]
   76 | struct FileMetaData

**Comment by Terrtia** [comment]
Hi @Azrara !

There is currently a workaround: https://github.com/CIRCL/AIL-framework/issues/369#issuecomment-624475481

We will most probably move to [kvrocks](https://github.com/bitleak/kvrocks) in a near future.

**Comment by Azrara** [comment]
Thank you @Terrtia
