### ISSUE TITLE
Backgroud Update: v1.5

### ISSUE THREAD

**Issue by mtps3** [CIRCL/AIL-framework#501]
I have a problem to synchronize the backgroud update

![image](https://user-images.githubusercontent.com/18214201/82098276-0559d900-96db-11ea-96f6-1ed99ba9c625.png)

I tried to run this command to fix it, update-background.py, but I was unsuccessful because another error appears and I couldn't solve it.

![image](https://user-images.githubusercontent.com/18214201/82098379-3df9b280-96db-11ea-82cb-0df2ebf82679.png)

**Comment by Terrtia** [comment]
Hi @mtps3 !
Thanks for the report !

Fixed with 399e37924118aa5353908ee017b021819830c1c1
