### ISSUE TITLE
Reseting the GUI admin password

### ISSUE THREAD

**Issue by Zakaren** [CIRCL/AIL-framework#502]
Hello, 

Is there a way to reset the GUI admin password ? 

Thank you,

**Comment by mokaddem** [comment]
Hey, this might be helpful
### Change Password
```
MISP/app/Console/cake Password [email] [new_password] [--override_password_change]
```

**Comment by mokaddem** [comment]
Replied with a solution for another software. Sorry for the confusion ;)

**Comment by Terrtia** [comment]
Hi @Zakaren !

I added a new option in the launcher. (85a0d944cc643c0bfc4fd475a2a7a418a7efaf85)
You can use the -rp option to reset the admin password: ``./LAUNCH.sh -rp``

**Comment by Zakaren** [comment]
Hi @Terrtia, 

It worked, thank you
