### ISSUE TITLE
Crawling error

### ISSUE THREAD

**Issue by rmsferreira** [CIRCL/AIL-framework#504]
HI,

when I start crawling onion sites, all appears down on dashboard.

After view the screen running the Crawler_AIL I have this error:

Traceback (most recent call last):
  File "./Crawler.py", line 413, in <module>
    crawler_config = load_crawler_config(to_crawl['type_service'], url_data['domain'], to_crawl['paste'],  to_crawl['url'], date)
  File "./Crawler.py", line 189, in load_crawler_config
    crawler_config['crawler_options'] = get_crawler_config(redis_crawler, 'auto', service_type, domain, url=url)
  File "./Crawler.py", line 173, in get_crawler_config
    crawler_options['time'] = int(config['time'])
KeyError: 'time'

**Comment by Terrtia** [comment]
Fixed: https://github.com/ail-project/ail-framework/issues/9
