### ISSUE TITLE
WEB Interface not starting

### ISSUE THREAD

**Issue by tinozyeah** [CIRCL/AIL-framework#508]
Hi, I've recently installed Ubuntu 18.04 and also AIL 3.1 and I can't open WEB Interface.
When I run ./LAUNCH.sh -l this is what I get:
![Screenshot_1](https://user-images.githubusercontent.com/37228247/83514094-402d8080-a4d3-11ea-9598-01d692cfcd02.png)

Also, I tried the screen -r Flask_AIL and screen -r -d Flask_AIL and this is output:
![Screenshot_2](https://user-images.githubusercontent.com/37228247/83514208-79fe8700-a4d3-11ea-9ebf-57dfd3691a79.png)

Can someone please help to resolve this issue, thanks.

**Comment by Terrtia** [comment]
Hi @tinozyeah !
Can you please try to attach to this screen with ``screen -D -r Flask_AIL`` or ``screen -D -r 1360``

**Comment by tinozyeah** [comment]
I tried both of these and get same output like before:
![Screenshot_3](https://user-images.githubusercontent.com/37228247/83523386-69a1d880-a4e2-11ea-9ae0-0b7f611bf27f.png)

**Comment by adulau** [comment]
You are already in a screen session. Do a "ctrl-a d" before reattaching to another screen session.

**Comment by tinozyeah** [comment]
I did it, now i get error:
![drugi_error](https://user-images.githubusercontent.com/37228247/83536057-0c625300-a4f3-11ea-95e5-1712e8b5e554.png)

**Comment by Terrtia** [comment]
You have an error in the custom module you added.

I can help you debug it if you provide the source code of  the ``Flask_Tino.py`` script.

**Comment by qanniej** [comment]
Hi all, 

I'm also facing the same issue where I can't launch the web interface. 

when I run the command screen -r, I get this output. 

**There are several suitable screens on:
        36460.Flask_AIL (06/23/2020 01:09:01 AM)        (Attached)
        36198.Script_AIL        (06/23/2020 01:08:54 AM)        (Detached)
        36031.Queue_AIL (06/23/2020 01:08:48 AM)        (Detached)
        35977.Logging_AIL       (06/23/2020 01:08:48 AM)        (Detached)
        35958.ARDB_AIL  (06/23/2020 01:08:48 AM)        (Detached)
        35931.Redis_AIL (06/23/2020 01:08:48 AM)        (Detached)
Type "screen [-d] -r [pid.]tty.host" to resume one of them.**

Please suggest what I should do.

**Comment by Terrtia** [comment]
Hi @qanniej  !

You are already in a screen session. Do a `ctrl-a d` before reattaching to the Flask screen session with ``screen -D -r Flask_AIL``

**Comment by mokaddem** [comment]
Seems to be solved
