### ISSUE TITLE
Disable storing ONION screenshots - no working

### ISSUE THREAD

**Issue by ttuuxxeerr** [CIRCL/AIL-framework#509]
Hi,
Since the last update the configuration option **default_crawler_png = false** is not working.   I am able to see the screenshots of the onion pages. 

version: 

AIL Version | v3.1 (release note)
-- | --
Current Branch | master
Current Commit ID | d6897904d6b3b7513a349b758fd94bd06a3f5e27
Current Tag | v3.1

Thanks for fixing it.

Regards

**Comment by Terrtia** [comment]
Hi @ttuuxxeerr !
Thanks for the report ! 

I found another issue in the UI selector of the manual crawler.
Fixed with d20ae355481f1087b26d400f937c5a4d3d291819.

**Comment by ttuuxxeerr** [comment]
Great thanks. I patched and it works.  Cheers.
