### ISSUE TITLE
Web interface not running

### ISSUE THREAD

**Issue by annetteshajan** [CIRCL/AIL-framework#510]
Hey is there any reason I'm getting 502 :Bad Gateway while I'm trying to open the link @Terrtia 
Also curl http://localhost:7000 doesn't give an output

**Comment by Terrtia** [comment]
Hi @annetteshajan !
Using https may solve your issue.

**Comment by annetteshajan** [comment]
![Screenshot from 2020-06-04 20-31-41](https://user-images.githubusercontent.com/44122967/83773762-93096280-a6a2-11ea-9e71-c3127e9d8146.png)
no..don't think it works :(

**Comment by annetteshajan** [comment]
Also can you explain the 502:Bad Gateway error and how to avoid it?
