### ISSUE TITLE
Leak hunter doesn't work

### ISSUE THREAD

**Issue by 5par0w** [CIRCL/AIL-framework#513]
Hello, 
Since we upgraded to v3.1 (the redis bases have been erased) the leak hunter module (word:set/regerx tracker) seems to be broken. 

Indeed, it is impossible to trigger keywords on platforms like Pastebin as we used to do before the upgrade.

The implemented expressions are well present in the redis database, and the test-zmq.py feeder is used. 

What can be the problem please ? 

Thank you for your help.

**Comment by garmorda** [comment]
I have same issue. I can not add a new traker. 

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
