### ISSUE TITLE
mv: cannot stat 'temp/jquery.canvasjs.min.js': No such file or directory

### ISSUE THREAD

**Issue by KyyB** [CIRCL/AIL-framework#520]
Hi,

While going through the installation step " ./installing_deps.sh ", I got the following error, " mv: cannot stat 'temp/jquery.canvasjs.min.js': No such file or directory". The path for "jquery.canvasjs.min.js" is  /ail-framework/var/www/temp/Chart 2.3.2 GA - Stable ".  Any idea on this issue? May you kindly assist with the error?

Thanks & Much Appreciated!

**Comment by Terrtia** [comment]
Hi @KyyB !
Thanks for the report !

Fixed with 7f9df2d08367c9a97d2cfcdec597e1e4ced28e0e
