### ISSUE TITLE
fatal: --unshallow on a complete repository does not make sense

### ISSUE THREAD

**Issue by KyyB** [CIRCL/AIL-framework#521]
Hi,

Got the error above when trying to install the solution. Is there a reason to this?
Also, when i try to run i get update error, why is that?

**Comment by Terrtia** [comment]
Hi @KyyB !

Thanks for the report ! Fixed with f71aef9f47cce977b7a485156ddfb2b0c4471796 

Can you please git pull and relaunch the installer ?
Tell me if it doesn't solve your issue with the updater.
