### ISSUE TITLE
Unable to get Feeder working

### ISSUE THREAD

**Issue by Jbhoohe** [CIRCL/AIL-framework#522]
Hey,

Was hoping you could provide a bit of help or guidance. I'm running Pystemon on Python 2.7 and AIL on pythong 3.6+.
I can't seem to get the feeder working via GUI or from the shell. I can see Pystemon running and AIL running but I can't seem to get it to work. Do you have any guidance or any where you can point me in the right direction? Also just to add on, I have other components of AIL working just fine like the crawler.

**Comment by Terrtia** [comment]
Hi @Jbhoohe !

Which version of pystemon are you using ?
Do you have any error in the pystemon output ? 
Are pastes save on disk (on pystemon side) ?
