### ISSUE TITLE
Bind 127.0.0.1 to 0.0.0.0

### ISSUE THREAD

**Issue by Finaud57** [CIRCL/AIL-framework#523]
Hello,
Which configs files have I to modify if I want to access to the we interface from another IP ?
Thank you

**Comment by Terrtia** [comment]
Hi @Finaud57 !
You can change the flask server host on the [configs/core.cfg](https://github.com/ail-project/ail-framework/blob/master/configs/core.cfg.sample#L43) file. You can do it by editing the `host` field of the `Flask` section.
Restart the Flask server after editing this config file.

**Comment by Finaud57** [comment]
Thank you very much :)
