### ISSUE TITLE
UnicodeDecodeError when running 'LAUNCH.sh' on a fresh Ubuntu install

### ISSUE THREAD

**Issue by fr0gger** [CIRCL/AIL-framework#525]
Hi, I have multiple UnicodeDecodeError exception when running LAUCH.sh -l for the first time on a fresh Ubuntu install. 
Below is the screenshot of the command "screen -r Flask_AIL". 

Thanks for your help :) 

<img width="803" alt="Screenshot 2020-09-25 at 11 07 15" src="https://user-images.githubusercontent.com/6546250/94248852-57c7c380-ff1f-11ea-91ba-0fd8446a7f16.png">

**Comment by Terrtia** [comment]
Hi @fr0gger !

This may be related to #321

On my machine with python3, this is what I get:

```
In [1]: import locale

In [2]: locale.getpreferredencoding(False)
Out[2]: 'UTF-8'

In [3]: locale.getpreferredencoding()
Out[3]: 'UTF-8'
```

Does it return ASCII for you?

**Comment by fr0gger** [comment]
Hi @Terrtia 

Thanks for your quick reply :) 

I have ANSI_X3.4-1968. Do you have a quick fix to change it to UTF-8?

```
>>> import locale
>>> locale.getpreferredencoding(False)
'ANSI_X3.4-1968'
>>> locale.getpreferredencoding()
'ANSI_X3.4-1968'
```

**Comment by fr0gger** [comment]
Okay just solved the issue by following the link you provided [#321](https://github.com/CIRCL/AIL-framework/issues/321)
Thanks!
