### ISSUE TITLE
Problems with Update to 3.2

### ISSUE THREAD

**Issue by garmorda** [CIRCL/AIL-framework#527]
Hi team,

I have problems to update from 3.1 to 3.2.
i create new folder under /home/ubuntu/AIL-framework/update/v3.2 and in this folder i paste both scripts: update.sh and update.py.

In the update i don't have problems but when start AIL no change my version.
Doing ./LAUNCH.sh -u I have"AIL not Updated" message.

Thanks

**Comment by Terrtia** [comment]
Fixed in v5.0
