### ISSUE TITLE
Installation problems Ubuntu 18.04 (ssdeep)

### ISSUE THREAD

**Issue by Gizter123** [CIRCL/AIL-framework#530]
The problem occured in the middle of installation. Using python 2.7, Ubuntu 18.04. Also it's VM of course. Should i use ansible?
Followed these instructions: 
```
git clone https://github.com/ail-project/ail-framework.git
cd ail-framework
./installing_deps.sh

cd ~/ail-framework/
cd bin/
./LAUNCH.sh -l
```

![image](https://user-images.githubusercontent.com/45005773/98251335-442d6500-1f81-11eb-88fe-41f592f1467c.png)

**Comment by hefesita** [comment]
The same here, did you found the cause?
