### ISSUE TITLE
installing_deps.sh error on Debian 10.6

### ISSUE THREAD

**Issue by leolanzi** [CIRCL/AIL-framework#531]
Following - I hope - [Installation](https://github.com/CIRCL/AIL-framework#installation),
I get:
`INFO: pip is looking at multiple versions of parsel to determine which version is compatible with other requirements. This could take a while.
  Using cached MarkupSafe-1.0.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/git/ail-framework/AILENV/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n1t9cngk/markupsafe_e5d744798cf14b8ba059ed6103e71da8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n1t9cngk/markupsafe_e5d744798cf14b8ba059ed6103e71da8/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gk69oqsj
         cwd: /tmp/pip-install-n1t9cngk/markupsafe_e5d744798cf14b8ba059ed6103e71da8/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n1t9cngk/markupsafe_e5d744798cf14b8ba059ed6103e71da8/setup.py", line 6, in <module>
        from setuptools import setup, Extension, Feature
    ImportError: cannot import name 'Feature' from 'setuptools' (/opt/git/ail-framework/AILENV/lib/python3.7/site-packages/setuptools/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Even forcing a`pip install -r requirements.txt`, before or after executing `installing_deps.sh`,  doesn't help.

Thank you!

**Comment by ChristianPao** [comment]
'Feature' was removed in setuptools version >=46. https://github.com/pypa/setuptools/issues/2017
`pip3 install setuptools==45` is a quick fix.

**Comment by Terrtia** [comment]
Fixed in v5.0
