### ISSUE TITLE
Web Interface issue

### ISSUE THREAD

**Issue by harryanon** [CIRCL/AIL-framework#533]
Unable to open web interface

**Comment by harryanon** [comment]
./LAUNCH.sh -l
	* Checking configuration
Config File: Nothing to update
Config File: Nothing to update
	* Configuration up-to-date
******************************************************************
*                        Updating AIL ...                        *
******************************************************************
Modified Files:
configs/6382.conf

Please, commit your changes or stash them before you can update AIL

Aborting ...
******************************************************************
*                    AIL Not Updated                             *
******************************************************************

	* Launching Redis servers
	* Launching ARDB servers
	* Launching logging process
	* Launching all the queues
	* Checking configuration
Config File: Nothing to update
Config File: Nothing to update
	* Configuration up-to-date
	* Launching scripts
	* Launching Flask server

**Comment by harryanon** [comment]
Unable to connect

Firefox can’t establish a connection to the server at localhost:7000.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

**Comment by gallypette** [comment]
Hi,

Make sure you use https to reach AIL https://127.0.0.1:7000
