### ISSUE TITLE
Pystemon Problems

### ISSUE THREAD

**Issue by Tango43** [CIRCL/AIL-framework#54]
Hi, i managed to install AIL-framework, but i am having problems figuring out how i activate the pystemon feeder to the AIL-framework, any help would be very helpful.
Thank you in advance

**Comment by Rafiot** [comment]
You have two possibilities: 
* setting up [pystemon](https://github.com/CIRCL/pystemon)
* [Contact us](info@circl.lu) and provide a static IP so we can give you access to our feed.

**Comment by Tango43** [comment]
Thank you for the answer.
I think using pystemon is the best option for my situationm my question is how do I configure it and run it so that it feeds the information to AIL framework, because if I just start them at the same time no information seems to be reaching AIL-framework.

**Comment by Tango43** [comment]
I have now managed to store the pystemon files in AIL-framework/PASTES and to import them with import -d /home/"user"/AIL-framework/PASTES, but this forces me to import them every few minutes to analyse them is there a way to automate this process?

**Comment by Rafiot** [comment]
We have a feeder, @adulau willl give it to you :)

**Comment by Tango43** [comment]
I don't need it anyways I managed to my feeder working :D
During the installation i got an error saying that jquery timers 1.0.0 path didn't exist anymore do you know, how much this will impact the program? I can't find anywhere else i can download it from.

**Comment by Tango43** [comment]
--2016-06-01 12:25:52--  https://collabdev.googlecode.com/svn-history/r5/trunk/static/js/jquery.timers-1.0.0.js
Resolving collabdev.googlecode.com (collabdev.googlecode.com)... 64.233.166.82, 2a00:1450:400c:c09::52
Connecting to collabdev.googlecode.com (collabdev.googlecode.com)|64.233.166.82|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-01 12:25:52 ERROR 404: Not Found.

**Comment by Tango43** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19688565/15850967/19df39a0-2c9b-11e6-8373-278b52783e5c.png)

**Comment by Rafiot** [comment]
yay, seems to work!

**Comment by Tango43** [comment]
My graph don't go down and look different from the ones on your pictures, could this be the jquery.timers ?

**Comment by Rafiot** [comment]
hmm, maybe. What happen if you reload the page?

**Comment by Tango43** [comment]
Nothing changes :/

**Comment by Rafiot** [comment]
I wonder where the jquery error comes from.

**Comment by Tango43** [comment]
Well to me it looks like the link is an old link and isn't valid anymore?

**Comment by Rafiot** [comment]
yeah, I didn't know we load external scripts...

**Comment by Tango43** [comment]
Yeah exactly

**Comment by Rafiot** [comment]
Can you try to get this one instead: https://raw.githubusercontent.com/jbrooksuk/jQuery-Timer-Plugin/master/jquery.timer.js ?

**Comment by Tango43** [comment]
Changed the lines in the update 3dr party script with the one u wrote, and then ran it again, but it didn't change anything still the exact same

**Comment by Rafiot** [comment]
are the values on the left side changing? And the logs (down the page)?

**Comment by Tango43** [comment]
Yes everything apart from the graphs seems to be working normaly

**Comment by Rafiot** [comment]
Hmmmm this is super weird, the graph comes from the values on the left. Can you open a debug console in your browser and and see if there are errors?

**Comment by Tango43** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19688565/15851787/9976650a-2c9e-11e6-81e1-687dd2f12397.png)

**Comment by Tango43** [comment]
Looks like that, btw sry I am just a intern that has been told to try this stuff out, not rly very comptetent with this stuff :D

**Comment by Tango43** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19688565/15851878/21b303e2-2c9f-11e6-9b02-58ce9f8952d1.png)
And wordstrending looks like this

**Comment by Rafiot** [comment]
Well, you got the framework too work, that's good :) 

I just looked more closely at the 1st graph, it is actually moving up a bit. Could it be that you receive more pastes you can actually process? The values on the left, are they only increasing?

**Comment by Tango43** [comment]
Yeah, well the graphs only go up but never down even when i turn off the pastes, and even if i limit pystemon heavily to only giving me very few pastes (via the search feature) the graphs will only go up and never down

**Comment by Tango43** [comment]
I will try and increase my processing power on my VMmachine now

**Comment by Tango43** [comment]
It seems like to many things to process might have been the problem, they queues never went down cause i keept slaming them with the feeder, ups. Well ty for the help anyways was very helpful, just wordtrending not working now, but that seems like its a http path error as the server gives me 404 erros when i click it in its logs.

**Comment by Rafiot** [comment]
`ail-framework/var/www/static/csv/wordtrendingdata.csv` <= could it be  permission issue?

**Comment by Tango43** [comment]
Yeah it is the issure for some reason that .csv file is just not there?

**Comment by Rafiot** [comment]
it is created on the fly, by the web interface, I think.

**Comment by Tango43** [comment]
I should be launching Pystemon-feeder and Flask_server.py from within the virtual environent? the on that says
(AILENV)user@AILserver:

**Comment by Tango43** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19688565/15854331/98274218-2ca9-11e6-8903-51b71d2a1ca4.png)
This is what it looks like now some of queues seem to not get processed at all

**Comment by Rafiot** [comment]
To look at the scripts, and see if they are working, connect to the screen (`screen -r`)and switch between the windows to see what is happening (`CTRL-a n`)

**Comment by Tango43** [comment]
Yeah every one of them are having seperate errors. Will try and fix and then get back to you

**Comment by Rafiot** [comment]
if you fix the code, please do a Pull Request :)

**Comment by Tango43** [comment]
if not exists_in(indexpath):
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 136, in exists_in
    ix = open_dir(dirname, indexname=indexname)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 123, in open_dir
    return FileIndex(storage, schema=schema, indexname=indexname)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 421, in __init__
    TOC.read(self.storage, self.indexname, schema=self._schema)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 632, in read
    check_size("int", _INT_SIZE)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/index.py", line 626, in check_size
    sz = stream.read_varint()
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/filedb/structfile.py", line 191, in read_varint
    return read_varint(self.read)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/whoosh/util/varints.py", line 102, in read_varint
    b = ord(readfn(1))
TypeError: ord() expected a character, but string of length 0 found

**Comment by Tango43** [comment]
I keep getting this error for the indexer, are my python packages just installed wrongly? and how should i install them properly?

**Comment by Tango43** [comment]
Traceback (most recent call last):
  File "./Curve.py", line 68, in <module>
    prev_score = r_serv1.hget(low_word, date)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 1857, in hget
    return self.execute_command('HGET', name, key)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:2013. Connection refused.

**Comment by Rafiot** [comment]
Glad you solved the problem, and sorry I didn't follow up on this...
