### ISSUE TITLE
Background Update

### ISSUE THREAD

**Issue by lucadigregorio** [CIRCL/AIL-framework#540]
Hi, i've installed AIL, and i have problem to synchronize the background update v1.5 (AIL version v3.4).
![photo_2021-01-21_08-58-17](https://user-images.githubusercontent.com/49645452/105374730-4dd17b00-5c08-11eb-8da7-5fe593ffc89e.jpg)
![photo_2021-01-21_09-08-11](https://user-images.githubusercontent.com/49645452/105374741-5033d500-5c08-11eb-934c-c7abc9b5af2d.jpg)
I also try to run some update script related to the tags but nothing changed

NOTE: with the version of AIL v3.3 all works perfectly

**Comment by Terrtia** [comment]
Hi @lucadigregorio @dagobertdebug !

Thanks for the report!

Fixed with 2fb03baf509775896f62245339be65f5b604f132

**Comment by lucadigregorio** [comment]
Thank you so much!
