### ISSUE TITLE
502 error after updating to 3.4

### ISSUE THREAD

**Issue by ttuuxxeerr** [CIRCL/AIL-framework#541]
Hi,

I updated our AIL instance to v3.4 (9d2962cd13b64909002218e29c7444a0c17602c8) with the command ./LAUNCH.sh -u  .

After stopping AIL and starting again, I am not able to reach the web interface having a 502 error. I don't see any error in the logs or in the starting script (./LAUNCH.sh -l).

Do you have any advise what to check now?

**Comment by lesleyxyz** [comment]
Is AIL behind a reverse proxy?
Are you sure that it is setup correctly?
Can you check the following command:
screen -r Flask_AIL

**Comment by lesleyxyz** [comment]
What python version are you using?
AIL Requires 3.6+, I'm using 3.7.
Pretty sure you're using <3.6 because the "f" syntax like on that line was added in 3.6

**Comment by ttuuxxeerr** [comment]
Unfortunately the same error after updating to 3.7 . Anything else I should check? 
![Capture](https://user-images.githubusercontent.com/6804744/118623273-5e65bc80-b7c8-11eb-8d95-03a32fb45700.JPG)

**Comment by Terrtia** [comment]
Hi @lesleyxyz !

The virtualenv is still using the old python version (you can see the current version in``ail-framework/AILENV/lib``)

You need to re-install the virtualenv:

```bash
cd ail-framework
# Stop AIL
./bin/LAUNCH.sh -k
# Delete old virtualenv
rm -r AILENV
# Install virtualenv
./install_virtualenv.sh
```

Let me know if this solve your issue.

**Comment by ttuuxxeerr** [comment]
the install_virtualenv gives the following error:

![Capture](https://user-images.githubusercontent.com/6804744/118631021-6543fd80-b7cf-11eb-9b10-7de008d252d8.JPG)

**Comment by Terrtia** [comment]
It seem like you also need to update virtualenv:

```bash
sudo pip install -U virtualenv
```

Could you update the vitualenv package and re-install AIL virtualenv ? (you need to delete the old one)
