### ISSUE TITLE
Var not defined in TermTrackerMod.py

### ISSUE THREAD

**Issue by osagit** [CIRCL/AIL-framework#545]
Line 83:84 of bin/TermTrackerMod.py

`except TimeoutException:
      print ("{0} processing timeout".format(paste.p_rel_path))`

There is no ref of **paste** var before

Could it be instead ?
`print ("{0} processing timeout".format(Item.get_item_filename(item_id)))`

**Comment by Terrtia** [comment]
Hi @osagit !

Thanks for the report! 
Fixed with 3bf42543086592968538cac807e229b2648a408f
