### ISSUE TITLE
Pastebin IP block

### ISSUE THREAD

**Issue by Tango43** [CIRCL/AIL-framework#55]
Hey, I have been using AIL-framework with pystemon, for awhile now and have managed to get my ip banned by pastebin.com, how do you manage to access the site continously? Did you pay for the subscription to avoid bans?

Thanks you in advance.

**Comment by adulau** [comment]
This is more related to the technique to gather information. If you want to get more details, you can drop an email at info(AT)circl(DOT)lu. Thank you.
