### ISSUE TITLE
feeder name from pystemon always set to default in dashboard

### ISSUE THREAD

**Issue by osagit** [CIRCL/AIL-framework#551]
On dashboard graph, feeder name is always set to the default `unnamed_feeder` when comming from pystemon.

default is set in core.cfg:
```ini
default_unnamed_feed_name = unnamed_feeder
```

Feeder name is search in `Mixer.py` line 94:
```yaml
feeder_name, paste_name = complete_paste.split('>>')
```

So, pystemon_feeder.py should probably add these rafters to the paste_name:
in pystemon_feeder.py around line 73, something like this:
```yaml
path_to_send = os.path.join(pastes_directory, item_id)
path_to_send = 'pystemon>>' + path_to_send
```

**Comment by Terrtia** [comment]
Fixed in v5.0
