### ISSUE TITLE
Pastebin being crawled by tor proxy

### ISSUE THREAD

**Issue by Skullack** [CIRCL/AIL-framework#552]
Hi
How do I prevent the system from crawling pastebin using the tor proxy.

I have tried the following
Turning tor service off and also choosing dont use splash crawler.

If tor serivce is down then nothing is crawled. 
If tor service run. 
Pastebin is crawled using tor proxy only causing issues with crawling pastebin seeing that I have to whitelist an IP address which obviously with tor is not whitelisted. 

Looking forward to your reply
I submitted same on gitter.com but no response from anyone there.

**Comment by Terrtia** [comment]
AIL is not crawling pastebin.
https://github.com/cvandeplas/pystemon
