### ISSUE TITLE
"Crawler Disabled"? 

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#555]
I upgraded my AIL instance, also installed ail-splash-manager but I can't connect all the dots!?
Do you have an HOWTO to connect the two components?
My crawler does not run since the upgrade...

**Comment by Terrtia** [comment]
Hi @xme !

I updated the [HOWTO](https://github.com/ail-project/ail-framework/blob/master/HOWTO.md#crawler) section.
You need to save the Splash manager url and API key via the UI.

Let me know if something is missing in the HOWTO

**Comment by xme** [comment]
Great, I was indeed some points. AIL is not connected to the new framework, everything is greeen.
However, I had to manually star the Flask server. What's your advice to launch it like the other components? Via a screen?

**Comment by Terrtia** [comment]
Fixed in v5.0
