### ISSUE TITLE
PasteSubmit

### ISSUE THREAD

**Issue by pemorphsm** [CIRCL/AIL-framework#562]
I am running 2 instances of the framework on my computer in virtual box. 
In the first one the virtual image from the circl.lu website is running. The second one is a Ubuntu 20.04 with github installation.
If I run the framework from the first vm there is no problem when submitting a file on the web interface, while the second vm does not upload the file. I get no error but a loading page. 
![Bildschirmfoto vom 2021-07-02 13-32-05](https://user-images.githubusercontent.com/86833321/124268574-faaa0f80-db39-11eb-9544-adb6af28ff44.png)

Is there any known workaround or documentation how to fix this problem?

**Comment by pemorphsm** [comment]
oh ehm in the second vm the framework is installed at /root/ail-framework/ and I always start the framework with root permissions

**Comment by kevin3567** [comment]
I am having the same issue right now. Is there any follow-up on this issue?

**Comment by Terrtia** [comment]
Hi @kevin3567 , @pemorphsm !
Fixed in v3.6
