### ISSUE TITLE
[submit_paste] ModuleNotFoundError: No module named 'sflock'

### ISSUE THREAD

**Issue by juju4** [CIRCL/AIL-framework#563]
sflock has been removed from requirements recently per https://github.com/CIRCL/AIL-framework/commit/0e0a77a86df5f680fe0e1fdd61e1f5fdf8e1a117#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552

but submit_paste still is using it and it make supervisor task failed in my ansible role
https://github.com/juju4/ansible-ail-framework/runs/3005081242?check_suite_focus=true#step:15:814

still present here
https://github.com/CIRCL/AIL-framework/blob/master/bin/LAUNCH.sh
and p7zip-full tagged sflock here
https://github.com/CIRCL/AIL-framework/blob/master/installing_deps.sh

is it plan for removal or just a forgotten dependency?

thanks

**Comment by Terrtia** [comment]
Hi @juju4 !
Thanks for the report !

sflock has been removed, we had some issue for python > 3.6

Fixed in https://github.com/ail-project/ail-framework/releases/tag/v3.6
