### ISSUE TITLE
YARA match

### ISSUE THREAD

**Issue by pedropf83** [CIRCL/AIL-framework#565]
Hello, Would there be any way to get the term that gave Yara's match? When you have many terms, it is difficult to find out which result was found. Thank you!

![Tracker_yara](https://user-images.githubusercontent.com/18240065/128448783-13da2e92-58fb-49ce-9762-3130ad7781bd.png)

**Comment by Terrtia** [comment]
First version to show extracted/tracked content added in AIL v5.0
YARA match are highlighted in the Item content

![Screenshot from 2023-06-06 10-50-24](https://github.com/CIRCL/AIL-framework/assets/8857208/f0e17980-9f59-45e5-853b-1cbab3c921b7)
