### ISSUE TITLE
Can’t create new tracker

### ISSUE THREAD

**Issue by xme** [CIRCL/AIL-framework#570]
Since the last upgrade (via ./LAUNCH -l), I can’t create a new tracker!? Any idea?
Here is the dumped error:

`[2021-12-07 20:17:37,751] ERROR in app: Exception on /tracker/add [GET] - Traceback (most recent call last):   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app     response = self.full_dispatch_request()   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request     rv = self.handle_user_exception(e)   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception     reraise(exc_type, exc_value, tb)   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise     raise value   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request     rv = self.dispatch_request()   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request     return self.view_functions[rule.endpoint](**req.view_args)   File "/opt/AIL-framework/AILENV/lib/python3.7/site-packages/flask_login/utils.py", line 272, in decorated_view     return func(*args, **kwargs)   File "./modules/Role_Manager.py", line 68, in decorated_view     return func(*args, **kwargs)   File "/opt/AIL-framework/var/www/modules/hunter/Flask_hunter.py", line 143, in add_tracked_menu     all_sources=item_basic.get_all_items_sources(r_list=True),   File "/opt/AIL-framework/bin/lib/item_basic.py", line 212, in get_all_items_sources     res = _get_dir_source_name(PASTES_FOLDER, filter_dir=filter_dir)   File "/opt/AIL-framework/bin/lib/item_basic.py", line 207, in _get_dir_source_name     l_sources_name = _get_dir_source_name(directory, source_name=src_name, l_sources_name=l_sources_name, filter_dir=filter_dir)   File "/opt/AIL-framework/bin/lib/item_basic.py", line 207, in _get_dir_source_name     l_sources_name = _get_dir_source_name(directory, source_name=src_name, l_sources_name=l_sources_name, filter_dir=filter_dir)   File "/opt/AIL-framework/bin/lib/item_basic.py", line 201, in _get_dir_source_name     l_sources_name.add(to_add) AttributeError: 'NoneType' object has no attribute 'add'`

**Comment by Terrtia** [comment]
Hi @xme !
Thanks for the report ! 
Should be fixed with 19846997d99a5068a7d2999ce3b8017f887c8317
Let me know if you can create/edit a tracker

**Comment by xme** [comment]
Patch applied and confirmed working! Tx!
