### ISSUE TITLE
Error while installing AIL : pybgpranking

### ISSUE THREAD

**Issue by itnsec** [CIRCL/AIL-framework#571]
Hi,

I tried to install AIL framework, on a fresh debian 11 and on a fresh Ubuntu 
During the ./installing_deps.sh i had the same issue on both distributions : 

>Collecting pybgpranking
  Cloning https://github.com/D4-project/BGP-Ranking.git/ to /tmp/pip-install-8v0qht79/pybgpranking_f275734a8c304d97bce32d6fb7fbdfc9

> Running command git clone --filter=blob:none -q https://github.com/D4-project/BGP-Ranking.git/ /tmp/pip-install-8v0qht79/pybgpranking_f275734a8c304d97bce32d6fb7fbdfc9

> Resolved https://github.com/D4-project/BGP-Ranking.git/ to commit 47fb89e6e14568400cff1db1dfc99128c5393dfb
> ERROR: pybgpranking from git+https://github.com/D4-project/BGP-Ranking.git/#egg=pybgpranking&subdirectory=client (from -r requirements.txt (line 56)) does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

Is there something i did miss ? 

Best regards

**Comment by Rafiot** [comment]
This commit fixes the issue: https://github.com/CIRCL/AIL-framework/commit/e4dedeed54c9c4dbd4a973194a8073c7a9d7cb87 (the package is not on PyPi).
