### ISSUE TITLE
Inquiry on accessing the web interface

### ISSUE THREAD

**Issue by amypanduh** [CIRCL/AIL-framework#573]
I was trying to install AIL on ubuntu.
I've already finished until here --> update_thirdparty.sh.
When running the Flask_server.py, I encounter this error.

![image](https://user-images.githubusercontent.com/98456344/151172113-63c54476-9dbf-439d-a01c-ab226c681275.png)

Is this the correct next step? How can I access the web interface?

**Comment by amypanduh** [comment]
This problem is similar to this one

https://github.com/CIRCL/AIL-framework/issues/86#issue-181081221

But I don't know how to run the .py file within the virtual environment :(

**Comment by Terrtia** [comment]
The installer failed to install the AILENV.
This issue has been fixed in newer versions.
