### ISSUE TITLE
ERROR - Please make sure you have a AIL-framework environment, au revoir

### ISSUE THREAD

**Issue by Yuriassisx** [CIRCL/AIL-framework#581]
I AM HAVING THIS PROBLEM WHILE RUNNING THE PROGRAM

**Comment by adulau** [comment]
First of all, when you use upper-case in digital communication, it means screaming. So for searching for support or help, it's not a good start.

Then, you might need to provide more information about your setup, version, operating system and especially error logs to handle your request. Thank you very much. Feel free to reopen this issue when you can give more information.
