### ISSUE TITLE
Please make sure you have a AIL-framework environment, au revoir

### ISSUE THREAD

**Issue by komangulo** [CIRCL/AIL-framework#582]
Hello, I get the error "Please make sure you have a AIL-framework environment, au revoir" after executing:
 ./LAUNCH.sh -l

This happens to me on parrot OS. I can't find any directory "AILENV".

Can anyone help me?

**Comment by Terrtia** [comment]
Hi @komangulo !
It seem like you have an issue with the installer. 
Can you relaunch the install script and gave me the error output ?

**Comment by komangulo** [comment]
> Hola@komangulo! Parece que tienes un problema con el instalador. ¿Puede reiniciar el script de instalación y me dio el resultado de error?

Hi, I have tried to install it two more times and I always get the same error.

[
![image](https://user-images.githubusercontent.com/43007108/169857492-76b232a7-10c8-4beb-ba74-43dfce0d2ef2.png)
](url)

**Comment by gallypette** [comment]
I guess it boils down to the error `ModuleNotFoundError: No module named 'virtualenv.activation.xonsh` that you get at the end of the install script. I am not familiar with parrot OS, but from a quick google search it looks like this can be related to interactions with previous installations of virtualenv.
Try removing virtualenv, using maybe  `apt-get remove python3-virtualenv` depending on your install and reinstall AIL.
