### ISSUE TITLE
Install issue via docker

### ISSUE THREAD

**Issue by stmtstk** [CIRCL/AIL-framework#589]
I tried to install `Analysis of Information Leaks` via docker (Ubuntu 22.04, Docker version 23.0.3) but encountered an error. 
It seems to fail during the build process of tlsh, which is cloned from https://github.com/trendmicro/tlsh.git.

I received the following error message:

> CMake Error at test/cmake_install.cmake:57 (file):
>   file does not recognize sub-command CREATE_LINK
> Call Stack (most recent call first):
>  cmake_install.cmake:43 (include)

Do you have any suggestions on how to fix this issue?

Thank you.

**Comment by alirf81** [comment]
I have the same issues.

**Comment by alirf81** [comment]
@stmtstk have you solved this issue?

**Comment by Terrtia** [comment]
The Docker installer is an external contribution and is not maintained.
If you want to install AIL in a container you can install it inside a [LXC](https://ail-project.org/blog/2022/03/09/Installing-AIL-in-LXC-container/) container.
I recommend to build it from scratch as the available container is outdated. (We plan to publish a new one for the v5.0)
