### ISSUE TITLE
pyFaub

### ISSUE THREAD

**Issue by Tango43** [CIRCL/AIL-framework#60]
Hi i am trying out the new version of AIL and almost everything seems to work, but only question is what is pyfaub? and how come i am getting a error saying it cant be imported from my webstats.py

Traceback (most recent call last):
  File "./WebStats.py", line 16, in <module>
    from pyfaup.faup import Faup
ImportError: No module named pyfaup.faup

Thank you in advance.

**Comment by Rafiot** [comment]
pyFaup is available there: https://github.com/stricaud/faup/tree/master/src/lib/bindings/python

Note that you'll need to install faup too.

**Comment by Tango43** [comment]
Now I have faup installed and it seems like it fixed the error with Webstats but just gave me the exact same error in URL.py instead :/

**Comment by Rafiot** [comment]
Oo this is weird. are you sure it complains about the exact same library, and not an other one?

**Comment by Tango43** [comment]
Hmm okay rebooted to try again and now i have both webstats.py and url.py saying there is no faup, even tho i have installed i even get a msg when i write: faup. Seems to me that faup is installed correctly and working, which is why i dont understand this error :/


"user"@Ail-tester:~$ faup

Usage: faup [options] url|file

Options:
-a      skip provided argument file open check
-b      Run the webserver in background
-c <snapshot>   compare with snapshot selected with -s
-d {delimiter}
        will separate the fields with the wanted delimiter
-e      empty lines are processed
-f {scheme|credential|subdomain|domain|domain_without_tld|host|tld|port|resource_path|query_string|fragment|url_type}
        field to extract
-l      prefix with the line number (csv only)
-o {csv,json,module}
        output csv or json at your convenience. You can also just let the modules handle it.
-p      print the header
-q      quiet mode, do not print anything
-r {N}  removes the last N chars from the url
-s <snapshot_name>      create a snapshot
-t      do not extract TLD > 1 (eg. only get 'uk' instead of 'co.uk')
-u      update the mozilla list
-w listen_ip:port
        starts webserver on the wanted ip:port

**Comment by Tango43** [comment]
Might it have something todo with faup not being in the virtual env?

**Comment by Rafiot** [comment]
Oh, yeah, if pyfaup isn't in the virtualenv, it will fail. faup has to be installed systemwide.

**Comment by Tango43** [comment]
If I first activate the virtual env and then do: faup, i get the samme result, surely this must mean that faup can be reached in the virtual env? I just followed the installation on the faup github not sure if I have done something wrong.
My faup looks like this not sure if there is anything wrong with it?


"user"@Ail-tester:~$ ldd /usr/local/bin/faup
        linux-vdso.so.1 =>  (0x00007fff788c5000)
        libfaupl.so.1 => /usr/local/lib/x86_64-linux-gnu/libfaupl.so.1 (0x00007f4688250000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f468804c000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4687e2e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4687a69000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4688492000)

**Comment by Rafiot** [comment]
I just tried and it works for me when I follow this FAQ: https://github.com/stricaud/faup#faq

make sure you install pyfaup in the virtualenv

**Comment by Tango43** [comment]
I see u have update the install scripts, I reinstalled AIL from the start and it works now.
I still had to set the ldd /usr/local/bin/faup command manualy.
In your install script u assume a path and my faup was somewhere else.
Don't know if u want to fix that or not tho.
Thank you
