### ISSUE TITLE
Please make sure you have a AIL-framework environment, au revoir

### ISSUE THREAD

**Issue by sidh104** [CIRCL/AIL-framework#602]
Can anyone help to make this frame work run.
root@sdesktop:/home/desktop/virtual/AIL-framework/bin# ./LAUNCH.sh 
Please make sure you have a AIL-framework environment, au revoir

**Comment by gallypette** [comment]
AILENV is not present, so it looks like you missed some steps following the doc:
```
# Clone the repo first
git clone https://github.com/ail-project/ail-framework.git
cd ail-framework

# For Debian and Ubuntu based distributions
./installing_deps.sh

# Launch ail
cd ~/ail-framework/
cd bin/
./LAUNCH.sh -l
```

**Comment by sidh104** [comment]
@gallypette thanks for responding but i did followed the same steps only.. still after that received this error. Please let me know if you need more information

**Comment by gallypette** [comment]
Are you sure every steps succeeded?

**Comment by sidh104** [comment]
./installing_deb.sh is getting executed no error being thrown up until then post that when i tried to run ie
# Launch ail
cd ~/ail-framework/
cd bin/
./LAUNCH.sh -l

facing this error "[Please make sure you have a AIL-framework environment, au revoir"

**Comment by gallypette** [comment]
Weird, `LAUNCH.sh -l` fails that way [it means that `~/ail-framework/AILENV/bin/python`  does not exists](https://github.com/CIRCL/AIL-framework/blob/bcaf7040b383ada9ffd531e6758ef8bc76817f8f/bin/LAUNCH.sh#L18C4-L18C4), but it should after the install script. 

Maybe try to launch `./install_virtualenv.sh` from ~/ail-framework`.

**Comment by sidh104** [comment]
tried ./install_virtualenv.sh from ~/ail-framework`.
created virtual environment CPython3.10.12.final.0-64 in 517ms
  creator CPython3Posix(dest=/home/sidharth/virtual/AIL-framework/AILENV, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.0.2, setuptools==59.6.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
./install_virtualenv.sh: line 13: ./AILENV/bin/activate: No such file or directory

May be it will be helpful if you can share me the OS config you are using and in case if any pre-requisites are needed to run the tool successfully
