### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by Tango43** [CIRCL/AIL-framework#61]
Hi I am seeing u guys are in full update mode so I will just point out some stuff I have seen which are abit weird, or not working to well. Sry that i cant just push myself but it's company policy where I work.
Curve.py and Webstats.py have connection erros on localhost:2013, Also the Creditcard regex seem to match way more than it should, my AIL is completely filled with false positives.

Traceback (most recent call last):
  File "./Curve.py", line 68, in <module>
    prev_score = r_serv1.hget(low_word, date)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 1857, in hget
    return self.execute_command('HGET', name, key)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/olivier/AIL-framework/AILENV/local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:2013. Connection refused.

**Comment by Tango43** [comment]
You can mark this as closed when u have read it just wanted to inform u of where i was having trouble

**Comment by Rafiot** [comment]
Thanks for the feedbacks: 
* the default config is fixed (connexions to localhost:2013)
* Creditcard regex definitely has false positives, but the module hasn't been updated recently, it is weird you have more false positives now than before.

**Comment by Tango43** [comment]
Well before I just deactivated Creditcard but now I tried using it and realised how many false positives there where, just wasnt sure you guys knew about it :)

**Comment by Rafiot** [comment]
If you have an idea how to improve it, please tell us :) (even if you cannot do pull requests)

**Comment by Tango43** [comment]
Well I think muting the categ.py output would be good, it just spams that it is sending it to the other .py scripts ( url.py, credicards.py, mail.py) even tho it is only forwarding to check if there is anything valid in the pasts. Which I think is kinda useless info and makes the interface less "clean".


This can be done my just putting a # infront of the last 4 lines.
And then the user could choose to see it all by removing these #.
This is only my preference tho, as I prefer AIL not have like 200 things showing up, but only show me stuff when it actualy matters. :)

![untitled](https://cloud.githubusercontent.com/assets/19688565/17016652/52c812b6-4f30-11e6-9d46-0f4732493fa7.png)

**Comment by Tango43** [comment]
But again this is just a preference thing, I just like it abit more "clean".

**Comment by Tango43** [comment]
Also I have a update pystemon.yaml for the pystemon github, but I am waiting for company rules to change to allow me to push it. I have added more paste sites, as well as update some old ones which where just giving me errors when accessing them. Unfortunately I am still getting blocked by pastebin.com after to many requests and I think the only way to solve this is by upgrading to a premium account to allow unlimited requests.

**Comment by Rafiot** [comment]
Oh, yeah, the categ script does a first split in the pastes, the one you want to look at is the CreditCard script, this one has actual regex on credit card numbers.
