### ISSUE TITLE
Webstats.py

### ISSUE THREAD

**Issue by Tango43** [CIRCL/AIL-framework#62]
Suddenly my webstats.py decided to stop working :/, what do you think is happening which shouldn't?

Traceback (most recent call last):
  File "./WebStats.py", line 133, in <module>
    month)
  File "/home/olivier/AIL-framework/bin/packages/lib_words.py", line 89, in create_curve_with_word_file
    with open(feederfilename, 'rb') as f:
IOError: [Errno 2] No such file or directory: '/home/olivier/AIL-framework/AILENV/faup/src/data/mozilla.tlds'

**Comment by Rafiot** [comment]
yeah, sorry, I changed the default path to this one in https://github.com/CIRCL/AIL-framework/blob/master/bin/packages/config.cfg.sample 
It was /home/olivier/AIL-framework/AILENV/lib/faup/src/data/mozilla.tlds

**Comment by Tango43** [comment]
But from what i can see the installing_deps.sh install faup in "/home/olivier/AIL-framework/faup/" and NOT "/home/olivier/AIL-framework/lib/faup"?
Are my paths wrong or is the install deps just not updated?

**Comment by Rafiot** [comment]
Sorry, I answered too fast. With the default install script, the path should be: 
* `$AIL_HOME/faup/src/data/mozilla.tlds`

Isn't it the case?

**Comment by Tango43** [comment]
Well okay i checked it is installed in:

- $AIL_HOME/faup/src/data/mozilla.tlds

But it seems to me that in the error I sent in the start it looks for it in:

-  $AIL_HOME/ALIENV/faup/src/data/mozilla.tlds

Which is why an error is produced

**Comment by Rafiot** [comment]
Sorry, my mistake. This is the expected path: https://github.com/CIRCL/AIL-framework/blob/master/bin/packages/config.cfg.sample#L12
