### ISSUE TITLE
Missing ".sh" within the installing_deps.sh

### ISSUE THREAD

**Issue by icepaule** [CIRCL/AIL-framework#67]
Hello,

just ran into an issue while installing.
Lien 42 within above scripts only mentions "./make" but it should be "./make.sh" to run from within the script.
At least on my Ubuntu.  :-)

Cheers
Marcus

**Comment by mokaddem** [comment]
Thanks!

It will be fixed soon.

Sami

**Comment by adulau** [comment]
Fixed. Thank you for the notification.
