### ISSUE TITLE
Leveldb error

### ISSUE THREAD

**Issue by Beercow** [CIRCL/AIL-framework#72]
![8-24-2016 3-21-00 pm](https://cloud.githubusercontent.com/assets/10360919/17946553/68a494e4-6a0e-11e6-9116-2de08202e92e.png)

**Comment by Beercow** [comment]
Problem fixed with latest commit.

**Comment by mokaddem** [comment]
Thank you for your feedback!

This error may happen because the directory 3016 is not present.
The install_deps.sh script has been updated.

I hope your problem is now solved.

Sami
