### ISSUE TITLE
Tabs disappearing

### ISSUE THREAD

**Issue by Beercow** [CIRCL/AIL-framework#73]
The tabs keep disappearing when I go to click on them.

Before:
![2016-08-24-231309_1366x768_scrot](https://cloud.githubusercontent.com/assets/10360919/17956600/c76efd60-6a50-11e6-87ed-55c9dfc3ee5e.png)

Hover over tabs:
![2016-08-24-231312_1366x768_scrot](https://cloud.githubusercontent.com/assets/10360919/17956607/d4853f5a-6a50-11e6-9a97-8999bf3c405c.png)

Any idea on how to fix this?

**Comment by mokaddem** [comment]
This is a weird behavior.. Also, your Dashboard page is not rendered correctly. It should look like this:

![Dashboard](https://raw.githubusercontent.com/CIRCL/AIL-framework/master/doc/screenshots/dashboard.png "AIL framework dashboard")

Could it be possible to paste your browser console ?

**Comment by Beercow** [comment]
![8-25-2016 8-22-10 am](https://cloud.githubusercontent.com/assets/10360919/17970664/2cdcbb82-6a9d-11e6-9ed2-9a6fcf919dbd.png)

**Comment by Beercow** [comment]
Looks like metismenu is missing, how can I add that?
![8-25-2016 9-02-51 am](https://cloud.githubusercontent.com/assets/10360919/17972011/da4d1546-6aa2-11e6-8274-d7fb6128f07d.png)

**Comment by mokaddem** [comment]
Metisemenu is not used anymore. The import has been removed. :)
However, this should not influence the page rendering.

Other errors concerning Dygraph and typeError are (for the moment) normal.

**Comment by Beercow** [comment]
Hmm. I tried building this twice now on Ubuntu server 14. I tryed IE, Chrome, and Firefox with the same reaults. Would a printout of the directory and folder structure help to narrow it down?

**Comment by mokaddem** [comment]
I don't think so.. Is the run of 'installing_deps.sh' and 'update_thirdparty.sh' scripts successful ?

**Comment by Beercow** [comment]
Yes. both of them are successful. There is an error in the 'update_thirdparty.sh' script where mkdir temp is called in the wrong place. I have not submitted a pull request or that yet.

**Comment by vinsf** [comment]
I am having exactly the same problem.

I am also wondering where to go and make it search for specific pastes, it or am I missing something?

**Comment by johnbeers** [comment]
I have the same problem, tabs dissapear above when you move the mouse over.

In addition to this, when webserver is running (Flask_server.py), I can see Broken pipes like this:

`Exception in thread Thread-525:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
`

I'm using Ubuntu 16.04 LTS, Firefox 48.0

**Comment by Rafiot** [comment]
Yeah, the broken pipe exception is known, but this should not impact the web interface.

Did you try with the latest commit on master? Because we don't have the problem on our instance.
If you are, we need to investigate further.

**Comment by Rafiot** [comment]
@vinsf the search bar in on the index. What do you mean?

**Comment by Beercow** [comment]
I'm having this problem on the latest build on a fresh install of Ubuntu server 14.04 64bit. I've been trying every commit sense I first reported this. They all end up the same, the interface does not render right and the tabs disappear if you try to hover over them. The last thing I heard was 10 days ago whe I was asked if both install scripts run successfully.

**Comment by Beercow** [comment]
I think what @vinsf means is how do you get results in the console. That is a different issue that I could assist on but until the new console renders right, there is no point in walking through that issue.

**Comment by Rafiot** [comment]
Well, I have absolutely no idea what could be going wrong...

Generally, the way I debug weirdness with JS is by looking browser console, and the one of chrome is generally more effective (plus if you do a right click. you can export the full dump). I think we will need that full dump to investigate more.

The screenshot doesn't contains anything that could be related to the problem you have, so it must be somewhere else.

**Comment by Beercow** [comment]
It will be a couple of days but I should be able to get that information for you. Thank you for letting me know what information you need.

**Comment by Beercow** [comment]
Console log from Chrome:
[1473162909935.txt](https://github.com/CIRCL/AIL-framework/files/456712/1473162909935.txt)

Screenshot:
![9-6-2016 7-55-39 am](https://cloud.githubusercontent.com/assets/10360919/18274315/7b392fb8-7407-11e6-981c-01d487dc10c7.png)

**Comment by Rafiot** [comment]
Ok, seem sb-admin-2.css gets a 404.

What does this command says: 
```
ls var/www/static/css/
```

**Comment by Beercow** [comment]
![9-7-2016 6-15-43 am](https://cloud.githubusercontent.com/assets/10360919/18310180/9944bd0e-74c2-11e6-8ba6-7e08f36648d8.png)

**Comment by Rafiot** [comment]
okay, can you try to rename sb-admin.css to sb-admin-2.css? For some reason, the name changed...

I'll upgrade the code if it fixes the issue.

**Comment by Beercow** [comment]
Changing the name results in this:
![9-7-2016 8-18-05 am](https://cloud.githubusercontent.com/assets/10360919/18313323/d06fb41c-74d3-11e6-9821-147e6c7cdce0.png)

Log output:
[1473254297668.log.txt](https://github.com/CIRCL/AIL-framework/files/459185/1473254297668.log.txt)

**Comment by almoc** [comment]
Same problem here!

**Comment by Rafiot** [comment]
Okay, none of the errors are related to that bug so I have no idea what is going on, nor how to fix it.
I probably won't have time to to a clean install to try it myself before I'm back in the office (the 26th).

**Comment by almoc** [comment]
Grab admin-sb-2.css from admin-sb web site and put it in the folder! Works

**Comment by Beercow** [comment]
Same here. I still think the install scripts need to be looked into. There still might be some things that are broken from a fresh install. Rafiot, can you look into the install scrips to make sure there is nothing else missing?

**Comment by Rafiot** [comment]
I'll definitely to a fresh install as soon as I'm back from holiday and make sure it is working as expected, it seems in fact fairly broken right now.

**Comment by Beercow** [comment]
Thank you for your time and effort. It is very much appreciated.
