### ISSUE TITLE
Error 404 for adns-python module installation

### ISSUE THREAD

**Issue by rivenz** [CIRCL/AIL-framework#76]
Hi CIRCL team,

I was trying to build a docker container with AIL framework and found a 404 error during the build process due to the following URL located in pip_packages_requirement.txt that could not be accessed anymore: 

http://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz

There is however an archive link available at the following URL (but I dont know for how long):

https://web.archive.org/web/20151223111838/https://adns-python.googlecode.com/files/adns-python-1.2.1.tar.gz

Best regards,

**Comment by daniel-gallagher** [comment]
The link I used was: 
https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/adns-python/adns-python-1.2.1.tar.gz

**Comment by Rafiot** [comment]
Thank you for the hint, we need to update the install script. Feel free to do a PR if you like.
