### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by nanocyber** [CIRCL/AIL-framework#78]
Hi CIRCL team,

I was trying to install AIL-framework and found an python error during run "pip install -r pip_packages_requirement.txt" section : 
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5h5xZQ/ssdeep/

[pyerror.txt](https://github.com/CIRCL/AIL-framework/files/453908/pyerror.txt)

Best Wishes

**Comment by Rafiot** [comment]
This error is due to a missing dependency: 
`c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory`

Assuming you're on Ubuntu. can you try to run
`apt-get install libffi-dev`

And then re-run 
`pip install -r pip_packages_requirement.txt`

If it solves the problem, do not hesitate to do a PR (or I do it myself if you prefer)

**Comment by nanocyber** [comment]
thanks for your attention
No, the problem is not there.
Problem occurs after running "ssdeep" :

`Collecting`` ssdeep (from -r pip_packages_requirement.txt (line 21)) 
      Using cached ssdeep-3.1.1.tar.gz
            Complete output from command python setup.py egg_info:
            no previously-included directories found matching 'documentation/_build'
            zip_safe flag not set; analyzing archive contents... `

Unfortunately, I do not know the way to be solved.

**Comment by nanocyber** [comment]
thanks for your attention
No, the problem is not there.
Problem occurs after running "ssdeep" :

`Collectingssdeep (from -r pip_packages_requirement.txt (line 21))`
     `Using cached ssdeep-3.1.1.tar.gz`
           `Complete output from command python setup.py egg_info:`
           `no previously-included directories found matching 'documentation/_build' `
           `zip_safe flag not set; analyzing archive contents...`

Unfortunately, I do not know the way to be solved.

**Comment by Rafiot** [comment]
Yes, the error I mentioned in my last message is caused by trying to install ssdeep without `libffi-dev` installed: 

```
Collecting ssdeep (from -r pip_packages_requirement.txt (line 21))
  Using cached ssdeep-3.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    no previously-included directories found matching 'documentation/_build'
    zip_safe flag not set; analyzing archive contents...
    six: module references __path__
    
    Installed /tmp/pip-build-5h5xZQ/ssdeep/.eggs/six-1.10.0-py2.7.egg
    Searching for cffi
    Reading https://pypi.python.org/simple/cffi/
    Downloading https://pypi.python.org/packages/83/3c/00b553fd05ae32f27b3637f705c413c4ce71290aa9b4c4764df694e906d9/cffi-1.7.0.tar.gz#md5=34122a545060cee58bab88feab57006d
    Best match: cffi 1.7.0
    Processing cffi-1.7.0.tar.gz
    Writing /tmp/easy_install-jZk4oX/cffi-1.7.0/setup.cfg
    Running cffi-1.7.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jZk4oX/cffi-1.7.0/egg-dist-tmp-_9tykh
==> c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
```

**Comment by Nicknam3** [comment]
I've the same error but i resolved it by installing libfuzzy-dev

`sudo apt-get install libfuzzy-dev`

**Comment by Rafiot** [comment]
thanks, keeping it open until I update the install script
