### ISSUE TITLE
There is no data

### ISSUE THREAD

**Issue by almoc** [CIRCL/AIL-framework#80]
Just fresh installed your software without errors (install-dep.sh, etc.)

launch everything through LAUNCH.sh with success (listen on 2016, 3016, 6379, etc...)

started the flask_server

then nothing

**Comment by almoc** [comment]
Do i have to launch the feeder pystemon or something?!

**Comment by Rafiot** [comment]
you need to feed AIL with pastes, yes. pystemon is the easiest way.

**Comment by Rafiot** [comment]
Closing then.
