### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by nanocyber** [CIRCL/AIL-framework#85]
Hi Dear
I've installed the tool without error.
However, no data will be displayed on the dashboard.
There's no such paste does not download.
How can I tell where is the problem.

**Comment by Rafiot** [comment]
I guess it's because pystemon[1] isn't feeding AIL. The alternative to installing it is to give us the static IP you're using for AIL and we give you access to our feed.

[1] https://github.com/CIRCL/pystemon

**Comment by nanocyber** [comment]
Should not it be installed with installing_deps.sh or update_thirdparty.sh ?
I would like to install it.
Please advise how to install it and comply with AIL.

**Comment by Rafiot** [comment]
It is an external standalone tool, and not necessary something you want to have on the same machine as AIL.

To install it, you need to run the pystemon[1] server, and run the feeder[2].

[1] https://github.com/CIRCL/pystemon/blob/master/pystemon.py
[2] https://github.com/CIRCL/AIL-framework/tree/master/bin/feeder

**Comment by SteveClement** [comment]
Dear @nanocyber this comes belated but we are cleaning up the issue queue :)

In case you are still interested in AIL we have released a VM. 

We have a Virtual Maching (Virtualbox) here: https://www.circl.lu/services/ail-training-materials/

You just need to log into the VM and you see how it should look.

We will add some explanatory pictures soon. As you need to start some of the services on first login (options 1-5, just select them and press enter to start the server, on the VM)
