### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nanocyber** [CIRCL/AIL-framework#86]
Hi
I run update_thirdparty.sh Then encountered an error when running Flask_server.py with the following error message : 

`Traceback (most recent call last):`
`  File "Flask_server.py", line 14, in <module>`
`    sys.path.append(os.path.join(os.environ['AIL_BIN'], 'packages/'))`
`  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__`
`    raise KeyError(key)`
`KeyError: 'AIL_BIN'`

**Comment by Rafiot** [comment]
You need to run `Flask_server.py` from within the virtual environment (the env variable is defined there).

**Comment by nanocyber** [comment]
Thank a lot
Best wishes
