### ISSUE TITLE
Sentiment Analysis Stuck

### ISSUE THREAD

**Issue by timhux123** [CIRCL/AIL-framework#90]
The "Sentiment Analysis" page is not reporting any data and the "SentimentAnalysis" queue under the Dashboard page is showing red (stuck).
The AIL logs are not reporting any issues that I can see.
Anyone experience this and know how to fix?
Thanks!

**Comment by mokaddem** [comment]
Hi, 
Thank you for the report,
The sentiment analysis module does not report anything in the AIL logs.
Can you check the output of the “SentimentAnalysis.py” module? Is there an error or does it seem to be stuck?

**Comment by timhux123** [comment]
Running the “SentimentAnalysis.py” module separately complained about not being able to find the path to the “nltk_data” directory.
I added the path to this directory under the “Search Path” section in data.py which is located under ~/AIL-framework/AILENV/lib/python2.7/site-packages/nltk.
Rebooted and now the Sentiment Analysis page is looking better and the SentimentAnalysis queue is not showing red/stuck under the Dashboard page. 

Thanks again for the assistance.
