### ISSUE TITLE
Daemon Run

### ISSUE THREAD

**Issue by rmsferreira** [CIRCL/AIL-framework#92]
I hall,
I`m trying to use AIl in daemon mode. How can i run AIL, pystmon feed on boot

**Comment by rmsferreira** [comment]
Can i run AIL outside venv, like cucko ou MISP

**Comment by Rafiot** [comment]
Well, you can, but it is really not recommended.... You need to export a bunch of variables, and it isn't supported.

To run it as daemon, you need to set all those env variables first.
